use clap::{ValueEnum, builder::PossibleValue};

use crate::components::licenses::license::License;

impl ValueEnum for License {
    fn to_possible_value(&self) -> Option<clap::builder::PossibleValue> {
        match self {
            Self::_0BSD => Some(PossibleValue::new("0BSD")),
            Self::_3DUSlicer1x0 => Some(PossibleValue::new("3D-Slicer-1.0")),
            Self::AAL => Some(PossibleValue::new("AAL")),
            Self::Abstyles => Some(PossibleValue::new("Abstyles")),
            Self::AdaCoreUdoc => Some(PossibleValue::new("AdaCore-doc")),
            Self::Adobe2006 => Some(PossibleValue::new("Adobe-2006")),
            Self::AdobeUDisplayUPostScript => Some(PossibleValue::new("Adobe-Display-PostScript")),
            Self::AdobeUGlyph => Some(PossibleValue::new("Adobe-Glyph")),
            Self::AdobeUUtopia => Some(PossibleValue::new("Adobe-Utopia")),
            Self::ADSL => Some(PossibleValue::new("ADSL")),
            Self::AdvancedUCrypticsUDictionary => {
                Some(PossibleValue::new("Advanced-Cryptics-Dictionary"))
            }
            Self::AFL1x1 => Some(PossibleValue::new("AFL-1.1")),
            Self::AFL1x2 => Some(PossibleValue::new("AFL-1.2")),
            Self::AFL2x0 => Some(PossibleValue::new("AFL-2.0")),
            Self::AFL2x1 => Some(PossibleValue::new("AFL-2.1")),
            Self::AFL3x0 => Some(PossibleValue::new("AFL-3.0")),
            Self::Afmparse => Some(PossibleValue::new("Afmparse")),
            Self::AGPL1x0Uonly => Some(PossibleValue::new("AGPL-1.0-only")),
            Self::AGPL1x0UorUlater => Some(PossibleValue::new("AGPL-1.0-or-later")),
            Self::AGPL3x0Uonly => Some(PossibleValue::new("AGPL-3.0-only")),
            Self::AGPL3x0UorUlater => Some(PossibleValue::new("AGPL-3.0-or-later")),
            Self::Aladdin => Some(PossibleValue::new("Aladdin")),
            Self::ALGLIBUDocumentation => Some(PossibleValue::new("ALGLIB-Documentation")),
            Self::AMDUnewlib => Some(PossibleValue::new("AMD-newlib")),
            Self::AMDPLPA => Some(PossibleValue::new("AMDPLPA")),
            Self::AML => Some(PossibleValue::new("AML")),
            Self::AMLUglslang => Some(PossibleValue::new("AML-glslang")),
            Self::AMPAS => Some(PossibleValue::new("AMPAS")),
            Self::ANTLRUPD => Some(PossibleValue::new("ANTLR-PD")),
            Self::ANTLRUPDUfallback => Some(PossibleValue::new("ANTLR-PD-fallback")),
            Self::AnyUOSI => Some(PossibleValue::new("any-OSI")),
            Self::AnyUOSIUperlUmodules => Some(PossibleValue::new("any-OSI-perl-modules")),
            Self::Apache1x0 => Some(PossibleValue::new("Apache-1.0")),
            Self::Apache1x1 => Some(PossibleValue::new("Apache-1.1")),
            Self::Apache2x0 => Some(PossibleValue::new("Apache-2.0")),
            Self::APAFML => Some(PossibleValue::new("APAFML")),
            Self::APL1x0 => Some(PossibleValue::new("APL-1.0")),
            Self::AppUs2p => Some(PossibleValue::new("App-s2p")),
            Self::APSL1x0 => Some(PossibleValue::new("APSL-1.0")),
            Self::APSL1x1 => Some(PossibleValue::new("APSL-1.1")),
            Self::APSL1x2 => Some(PossibleValue::new("APSL-1.2")),
            Self::APSL2x0 => Some(PossibleValue::new("APSL-2.0")),
            Self::Arphic1999 => Some(PossibleValue::new("Arphic-1999")),
            Self::Artistic1x0 => Some(PossibleValue::new("Artistic-1.0")),
            Self::Artistic1x0Ucl8 => Some(PossibleValue::new("Artistic-1.0-cl8")),
            Self::Artistic1x0UPerl => Some(PossibleValue::new("Artistic-1.0-Perl")),
            Self::Artistic2x0 => Some(PossibleValue::new("Artistic-2.0")),
            Self::ArtisticUdist => Some(PossibleValue::new("Artistic-dist")),
            Self::AspellURU => Some(PossibleValue::new("Aspell-RU")),
            Self::ASWFUDigitalUAssets1x0 => Some(PossibleValue::new("ASWF-Digital-Assets-1.0")),
            Self::ASWFUDigitalUAssets1x1 => Some(PossibleValue::new("ASWF-Digital-Assets-1.1")),
            Self::Baekmuk => Some(PossibleValue::new("Baekmuk")),
            Self::Bahyph => Some(PossibleValue::new("Bahyph")),
            Self::Barr => Some(PossibleValue::new("Barr")),
            Self::BcryptUSolarUDesigner => Some(PossibleValue::new("bcrypt-Solar-Designer")),
            Self::Beerware => Some(PossibleValue::new("Beerware")),
            Self::BitstreamUCharter => Some(PossibleValue::new("Bitstream-Charter")),
            Self::BitstreamUVera => Some(PossibleValue::new("Bitstream-Vera")),
            Self::BitTorrent1x0 => Some(PossibleValue::new("BitTorrent-1.0")),
            Self::BitTorrent1x1 => Some(PossibleValue::new("BitTorrent-1.1")),
            Self::Blessing => Some(PossibleValue::new("blessing")),
            Self::BlueOak1x0x0 => Some(PossibleValue::new("BlueOak-1.0.0")),
            Self::BoehmUGC => Some(PossibleValue::new("Boehm-GC")),
            Self::BoehmUGCUwithoutUfee => Some(PossibleValue::new("Boehm-GC-without-fee")),
            Self::BOLA1x1 => Some(PossibleValue::new("BOLA-1.1")),
            Self::Borceux => Some(PossibleValue::new("Borceux")),
            Self::BrianUGladman2UClause => Some(PossibleValue::new("Brian-Gladman-2-Clause")),
            Self::BrianUGladman3UClause => Some(PossibleValue::new("Brian-Gladman-3-Clause")),
            Self::BSD1UClause => Some(PossibleValue::new("BSD-1-Clause")),
            Self::BSD2UClause => Some(PossibleValue::new("BSD-2-Clause")),
            Self::BSD2UClauseUDarwin => Some(PossibleValue::new("BSD-2-Clause-Darwin")),
            Self::BSD2UClauseUfirstUlines => Some(PossibleValue::new("BSD-2-Clause-first-lines")),
            Self::BSD2UClauseUPatent => Some(PossibleValue::new("BSD-2-Clause-Patent")),
            Self::BSD2UClauseUpkgconfUdisclaimer => {
                Some(PossibleValue::new("BSD-2-Clause-pkgconf-disclaimer"))
            }
            Self::BSD2UClauseUViews => Some(PossibleValue::new("BSD-2-Clause-Views")),
            Self::BSD3UClause => Some(PossibleValue::new("BSD-3-Clause")),
            Self::BSD3UClauseUacpica => Some(PossibleValue::new("BSD-3-Clause-acpica")),
            Self::BSD3UClauseUAttribution => Some(PossibleValue::new("BSD-3-Clause-Attribution")),
            Self::BSD3UClauseUClear => Some(PossibleValue::new("BSD-3-Clause-Clear")),
            Self::BSD3UClauseUflex => Some(PossibleValue::new("BSD-3-Clause-flex")),
            Self::BSD3UClauseUHP => Some(PossibleValue::new("BSD-3-Clause-HP")),
            Self::BSD3UClauseULBNL => Some(PossibleValue::new("BSD-3-Clause-LBNL")),
            Self::BSD3UClauseUModification => Some(PossibleValue::new("BSD-3-Clause-Modification")),
            Self::BSD3UClauseUNoUMilitaryULicense => {
                Some(PossibleValue::new("BSD-3-Clause-No-Military-License"))
            }
            Self::BSD3UClauseUNoUNuclearULicense => {
                Some(PossibleValue::new("BSD-3-Clause-No-Nuclear-License"))
            }
            Self::BSD3UClauseUNoUNuclearULicense2014 => {
                Some(PossibleValue::new("BSD-3-Clause-No-Nuclear-License-2014"))
            }
            Self::BSD3UClauseUNoUNuclearUWarranty => {
                Some(PossibleValue::new("BSD-3-Clause-No-Nuclear-Warranty"))
            }
            Self::BSD3UClauseUOpenUMPI => Some(PossibleValue::new("BSD-3-Clause-Open-MPI")),
            Self::BSD3UClauseUSun => Some(PossibleValue::new("BSD-3-Clause-Sun")),
            Self::BSD3UClauseUTso => Some(PossibleValue::new("BSD-3-Clause-Tso")),
            Self::BSD4UClause => Some(PossibleValue::new("BSD-4-Clause")),
            Self::BSD4UClauseUShortened => Some(PossibleValue::new("BSD-4-Clause-Shortened")),
            Self::BSD4UClauseUUC => Some(PossibleValue::new("BSD-4-Clause-UC")),
            Self::BSD4x3RENO => Some(PossibleValue::new("BSD-4.3RENO")),
            Self::BSD4x3TAHOE => Some(PossibleValue::new("BSD-4.3TAHOE")),
            Self::BSDUAdvertisingUAcknowledgement => {
                Some(PossibleValue::new("BSD-Advertising-Acknowledgement"))
            }
            Self::BSDUAttributionUHPNDUdisclaimer => {
                Some(PossibleValue::new("BSD-Attribution-HPND-disclaimer"))
            }
            Self::BSDUInfernoUNettverk => Some(PossibleValue::new("BSD-Inferno-Nettverk")),
            Self::BSDUMarkUModifications => Some(PossibleValue::new("BSD-Mark-Modifications")),
            Self::BSDUProtection => Some(PossibleValue::new("BSD-Protection")),
            Self::BSDUSourceUbeginningUfile => {
                Some(PossibleValue::new("BSD-Source-beginning-file"))
            }
            Self::BSDUSourceUCode => Some(PossibleValue::new("BSD-Source-Code")),
            Self::BSDUSystemics => Some(PossibleValue::new("BSD-Systemics")),
            Self::BSDUSystemicsUW3Works => Some(PossibleValue::new("BSD-Systemics-W3Works")),
            Self::BSL1x0 => Some(PossibleValue::new("BSL-1.0")),
            Self::Buddy => Some(PossibleValue::new("Buddy")),
            Self::BUSL1x1 => Some(PossibleValue::new("BUSL-1.1")),
            Self::Bzip21x0x6 => Some(PossibleValue::new("bzip2-1.0.6")),
            Self::CUUDA1x0 => Some(PossibleValue::new("C-UDA-1.0")),
            Self::CAL1x0 => Some(PossibleValue::new("CAL-1.0")),
            Self::CAL1x0UCombinedUWorkUException => {
                Some(PossibleValue::new("CAL-1.0-Combined-Work-Exception"))
            }
            Self::Caldera => Some(PossibleValue::new("Caldera")),
            Self::CalderaUnoUpreamble => Some(PossibleValue::new("Caldera-no-preamble")),
            Self::CAPECUtou => Some(PossibleValue::new("CAPEC-tou")),
            Self::Catharon => Some(PossibleValue::new("Catharon")),
            Self::CATOSL1x1 => Some(PossibleValue::new("CATOSL-1.1")),
            Self::CCUBY1x0 => Some(PossibleValue::new("CC-BY-1.0")),
            Self::CCUBY2x0 => Some(PossibleValue::new("CC-BY-2.0")),
            Self::CCUBY2x5 => Some(PossibleValue::new("CC-BY-2.5")),
            Self::CCUBY2x5UAU => Some(PossibleValue::new("CC-BY-2.5-AU")),
            Self::CCUBY3x0 => Some(PossibleValue::new("CC-BY-3.0")),
            Self::CCUBY3x0UAT => Some(PossibleValue::new("CC-BY-3.0-AT")),
            Self::CCUBY3x0UAU => Some(PossibleValue::new("CC-BY-3.0-AU")),
            Self::CCUBY3x0UDE => Some(PossibleValue::new("CC-BY-3.0-DE")),
            Self::CCUBY3x0UIGO => Some(PossibleValue::new("CC-BY-3.0-IGO")),
            Self::CCUBY3x0UNL => Some(PossibleValue::new("CC-BY-3.0-NL")),
            Self::CCUBY3x0UUS => Some(PossibleValue::new("CC-BY-3.0-US")),
            Self::CCUBY4x0 => Some(PossibleValue::new("CC-BY-4.0")),
            Self::CCUBYUNC1x0 => Some(PossibleValue::new("CC-BY-NC-1.0")),
            Self::CCUBYUNC2x0 => Some(PossibleValue::new("CC-BY-NC-2.0")),
            Self::CCUBYUNC2x5 => Some(PossibleValue::new("CC-BY-NC-2.5")),
            Self::CCUBYUNC3x0 => Some(PossibleValue::new("CC-BY-NC-3.0")),
            Self::CCUBYUNC3x0UDE => Some(PossibleValue::new("CC-BY-NC-3.0-DE")),
            Self::CCUBYUNC4x0 => Some(PossibleValue::new("CC-BY-NC-4.0")),
            Self::CCUBYUNCUND1x0 => Some(PossibleValue::new("CC-BY-NC-ND-1.0")),
            Self::CCUBYUNCUND2x0 => Some(PossibleValue::new("CC-BY-NC-ND-2.0")),
            Self::CCUBYUNCUND2x5 => Some(PossibleValue::new("CC-BY-NC-ND-2.5")),
            Self::CCUBYUNCUND3x0 => Some(PossibleValue::new("CC-BY-NC-ND-3.0")),
            Self::CCUBYUNCUND3x0UDE => Some(PossibleValue::new("CC-BY-NC-ND-3.0-DE")),
            Self::CCUBYUNCUND3x0UIGO => Some(PossibleValue::new("CC-BY-NC-ND-3.0-IGO")),
            Self::CCUBYUNCUND4x0 => Some(PossibleValue::new("CC-BY-NC-ND-4.0")),
            Self::CCUBYUNCUSA1x0 => Some(PossibleValue::new("CC-BY-NC-SA-1.0")),
            Self::CCUBYUNCUSA2x0 => Some(PossibleValue::new("CC-BY-NC-SA-2.0")),
            Self::CCUBYUNCUSA2x0UDE => Some(PossibleValue::new("CC-BY-NC-SA-2.0-DE")),
            Self::CCUBYUNCUSA2x0UFR => Some(PossibleValue::new("CC-BY-NC-SA-2.0-FR")),
            Self::CCUBYUNCUSA2x0UUK => Some(PossibleValue::new("CC-BY-NC-SA-2.0-UK")),
            Self::CCUBYUNCUSA2x5 => Some(PossibleValue::new("CC-BY-NC-SA-2.5")),
            Self::CCUBYUNCUSA3x0 => Some(PossibleValue::new("CC-BY-NC-SA-3.0")),
            Self::CCUBYUNCUSA3x0UDE => Some(PossibleValue::new("CC-BY-NC-SA-3.0-DE")),
            Self::CCUBYUNCUSA3x0UIGO => Some(PossibleValue::new("CC-BY-NC-SA-3.0-IGO")),
            Self::CCUBYUNCUSA4x0 => Some(PossibleValue::new("CC-BY-NC-SA-4.0")),
            Self::CCUBYUND1x0 => Some(PossibleValue::new("CC-BY-ND-1.0")),
            Self::CCUBYUND2x0 => Some(PossibleValue::new("CC-BY-ND-2.0")),
            Self::CCUBYUND2x5 => Some(PossibleValue::new("CC-BY-ND-2.5")),
            Self::CCUBYUND3x0 => Some(PossibleValue::new("CC-BY-ND-3.0")),
            Self::CCUBYUND3x0UDE => Some(PossibleValue::new("CC-BY-ND-3.0-DE")),
            Self::CCUBYUND4x0 => Some(PossibleValue::new("CC-BY-ND-4.0")),
            Self::CCUBYUSA1x0 => Some(PossibleValue::new("CC-BY-SA-1.0")),
            Self::CCUBYUSA2x0 => Some(PossibleValue::new("CC-BY-SA-2.0")),
            Self::CCUBYUSA2x0UUK => Some(PossibleValue::new("CC-BY-SA-2.0-UK")),
            Self::CCUBYUSA2x1UJP => Some(PossibleValue::new("CC-BY-SA-2.1-JP")),
            Self::CCUBYUSA2x5 => Some(PossibleValue::new("CC-BY-SA-2.5")),
            Self::CCUBYUSA3x0 => Some(PossibleValue::new("CC-BY-SA-3.0")),
            Self::CCUBYUSA3x0UAT => Some(PossibleValue::new("CC-BY-SA-3.0-AT")),
            Self::CCUBYUSA3x0UDE => Some(PossibleValue::new("CC-BY-SA-3.0-DE")),
            Self::CCUBYUSA3x0UIGO => Some(PossibleValue::new("CC-BY-SA-3.0-IGO")),
            Self::CCUBYUSA4x0 => Some(PossibleValue::new("CC-BY-SA-4.0")),
            Self::CCUPDDC => Some(PossibleValue::new("CC-PDDC")),
            Self::CCUPDM1x0 => Some(PossibleValue::new("CC-PDM-1.0")),
            Self::CCUSA1x0 => Some(PossibleValue::new("CC-SA-1.0")),
            Self::CC01x0 => Some(PossibleValue::new("CC0-1.0")),
            Self::CDDL1x0 => Some(PossibleValue::new("CDDL-1.0")),
            Self::CDDL1x1 => Some(PossibleValue::new("CDDL-1.1")),
            Self::CDL1x0 => Some(PossibleValue::new("CDL-1.0")),
            Self::CDLAUPermissive1x0 => Some(PossibleValue::new("CDLA-Permissive-1.0")),
            Self::CDLAUPermissive2x0 => Some(PossibleValue::new("CDLA-Permissive-2.0")),
            Self::CDLAUSharing1x0 => Some(PossibleValue::new("CDLA-Sharing-1.0")),
            Self::CECILL1x0 => Some(PossibleValue::new("CECILL-1.0")),
            Self::CECILL1x1 => Some(PossibleValue::new("CECILL-1.1")),
            Self::CECILL2x0 => Some(PossibleValue::new("CECILL-2.0")),
            Self::CECILL2x1 => Some(PossibleValue::new("CECILL-2.1")),
            Self::CECILLUB => Some(PossibleValue::new("CECILL-B")),
            Self::CECILLUC => Some(PossibleValue::new("CECILL-C")),
            Self::CERNUOHL1x1 => Some(PossibleValue::new("CERN-OHL-1.1")),
            Self::CERNUOHL1x2 => Some(PossibleValue::new("CERN-OHL-1.2")),
            Self::CERNUOHLUP2x0 => Some(PossibleValue::new("CERN-OHL-P-2.0")),
            Self::CERNUOHLUS2x0 => Some(PossibleValue::new("CERN-OHL-S-2.0")),
            Self::CERNUOHLUW2x0 => Some(PossibleValue::new("CERN-OHL-W-2.0")),
            Self::CFITSIO => Some(PossibleValue::new("CFITSIO")),
            Self::CheckUcvs => Some(PossibleValue::new("check-cvs")),
            Self::Checkmk => Some(PossibleValue::new("checkmk")),
            Self::ClArtistic => Some(PossibleValue::new("ClArtistic")),
            Self::Clips => Some(PossibleValue::new("Clips")),
            Self::CMUUMach => Some(PossibleValue::new("CMU-Mach")),
            Self::CMUUMachUnodoc => Some(PossibleValue::new("CMU-Mach-nodoc")),
            Self::CNRIUJython => Some(PossibleValue::new("CNRI-Jython")),
            Self::CNRIUPython => Some(PossibleValue::new("CNRI-Python")),
            Self::CNRIUPythonUGPLUCompatible => {
                Some(PossibleValue::new("CNRI-Python-GPL-Compatible"))
            }
            Self::COIL1x0 => Some(PossibleValue::new("COIL-1.0")),
            Self::CommunityUSpec1x0 => Some(PossibleValue::new("Community-Spec-1.0")),
            Self::Condor1x1 => Some(PossibleValue::new("Condor-1.1")),
            Self::CopyleftUnext0x3x0 => Some(PossibleValue::new("copyleft-next-0.3.0")),
            Self::CopyleftUnext0x3x1 => Some(PossibleValue::new("copyleft-next-0.3.1")),
            Self::CornellULosslessUJPEG => Some(PossibleValue::new("Cornell-Lossless-JPEG")),
            Self::CPAL1x0 => Some(PossibleValue::new("CPAL-1.0")),
            Self::CPL1x0 => Some(PossibleValue::new("CPL-1.0")),
            Self::CPOL1x02 => Some(PossibleValue::new("CPOL-1.02")),
            Self::Cronyx => Some(PossibleValue::new("Cronyx")),
            Self::Crossword => Some(PossibleValue::new("Crossword")),
            Self::CryptoSwift => Some(PossibleValue::new("CryptoSwift")),
            Self::CrystalStacker => Some(PossibleValue::new("CrystalStacker")),
            Self::CUAUOPL1x0 => Some(PossibleValue::new("CUA-OPL-1.0")),
            Self::Cube => Some(PossibleValue::new("Cube")),
            Self::Curl => Some(PossibleValue::new("curl")),
            Self::CveUtou => Some(PossibleValue::new("cve-tou")),
            Self::DUFSL1x0 => Some(PossibleValue::new("D-FSL-1.0")),
            Self::DEC3UClause => Some(PossibleValue::new("DEC-3-Clause")),
            Self::Diffmark => Some(PossibleValue::new("diffmark")),
            Self::DLUDEUBY2x0 => Some(PossibleValue::new("DL-DE-BY-2.0")),
            Self::DLUDEUZERO2x0 => Some(PossibleValue::new("DL-DE-ZERO-2.0")),
            Self::DOC => Some(PossibleValue::new("DOC")),
            Self::DocBookUDTD => Some(PossibleValue::new("DocBook-DTD")),
            Self::DocBookUSchema => Some(PossibleValue::new("DocBook-Schema")),
            Self::DocBookUStylesheet => Some(PossibleValue::new("DocBook-Stylesheet")),
            Self::DocBookUXML => Some(PossibleValue::new("DocBook-XML")),
            Self::Dotseqn => Some(PossibleValue::new("Dotseqn")),
            Self::DRL1x0 => Some(PossibleValue::new("DRL-1.0")),
            Self::DRL1x1 => Some(PossibleValue::new("DRL-1.1")),
            Self::DSDP => Some(PossibleValue::new("DSDP")),
            Self::Dtoa => Some(PossibleValue::new("dtoa")),
            Self::Dvipdfm => Some(PossibleValue::new("dvipdfm")),
            Self::ECL1x0 => Some(PossibleValue::new("ECL-1.0")),
            Self::ECL2x0 => Some(PossibleValue::new("ECL-2.0")),
            Self::EFL1x0 => Some(PossibleValue::new("EFL-1.0")),
            Self::EFL2x0 => Some(PossibleValue::new("EFL-2.0")),
            Self::EGenix => Some(PossibleValue::new("eGenix")),
            Self::Elastic2x0 => Some(PossibleValue::new("Elastic-2.0")),
            Self::Entessa => Some(PossibleValue::new("Entessa")),
            Self::EPICS => Some(PossibleValue::new("EPICS")),
            Self::EPL1x0 => Some(PossibleValue::new("EPL-1.0")),
            Self::EPL2x0 => Some(PossibleValue::new("EPL-2.0")),
            Self::ErlPL1x1 => Some(PossibleValue::new("ErlPL-1.1")),
            Self::ESAUPLUpermissive2x4 => Some(PossibleValue::new("ESA-PL-permissive-2.4")),
            Self::ESAUPLUstrongUcopyleft2x4 => {
                Some(PossibleValue::new("ESA-PL-strong-copyleft-2.4"))
            }
            Self::ESAUPLUweakUcopyleft2x4 => Some(PossibleValue::new("ESA-PL-weak-copyleft-2.4")),
            Self::Etalab2x0 => Some(PossibleValue::new("etalab-2.0")),
            Self::EUDatagrid => Some(PossibleValue::new("EUDatagrid")),
            Self::EUPL1x0 => Some(PossibleValue::new("EUPL-1.0")),
            Self::EUPL1x1 => Some(PossibleValue::new("EUPL-1.1")),
            Self::EUPL1x2 => Some(PossibleValue::new("EUPL-1.2")),
            Self::Eurosym => Some(PossibleValue::new("Eurosym")),
            Self::Fair => Some(PossibleValue::new("Fair")),
            Self::FBM => Some(PossibleValue::new("FBM")),
            Self::FDKUAAC => Some(PossibleValue::new("FDK-AAC")),
            Self::FergusonUTwofish => Some(PossibleValue::new("Ferguson-Twofish")),
            Self::Frameworx1x0 => Some(PossibleValue::new("Frameworx-1.0")),
            Self::FreeBSDUDOC => Some(PossibleValue::new("FreeBSD-DOC")),
            Self::FreeImage => Some(PossibleValue::new("FreeImage")),
            Self::FSFAP => Some(PossibleValue::new("FSFAP")),
            Self::FSFAPUnoUwarrantyUdisclaimer => {
                Some(PossibleValue::new("FSFAP-no-warranty-disclaimer"))
            }
            Self::FSFUL => Some(PossibleValue::new("FSFUL")),
            Self::FSFULLR => Some(PossibleValue::new("FSFULLR")),
            Self::FSFULLRSD => Some(PossibleValue::new("FSFULLRSD")),
            Self::FSFULLRWD => Some(PossibleValue::new("FSFULLRWD")),
            Self::FSL1x1UALv2 => Some(PossibleValue::new("FSL-1.1-ALv2")),
            Self::FSL1x1UMIT => Some(PossibleValue::new("FSL-1.1-MIT")),
            Self::FTL => Some(PossibleValue::new("FTL")),
            Self::Furuseth => Some(PossibleValue::new("Furuseth")),
            Self::Fwlw => Some(PossibleValue::new("fwlw")),
            Self::GameUProgrammingUGems => Some(PossibleValue::new("Game-Programming-Gems")),
            Self::GCRUdocs => Some(PossibleValue::new("GCR-docs")),
            Self::GD => Some(PossibleValue::new("GD")),
            Self::GenericUxts => Some(PossibleValue::new("generic-xts")),
            Self::GFDL1x1UinvariantsUonly => Some(PossibleValue::new("GFDL-1.1-invariants-only")),
            Self::GFDL1x1UinvariantsUorUlater => {
                Some(PossibleValue::new("GFDL-1.1-invariants-or-later"))
            }
            Self::GFDL1x1UnoUinvariantsUonly => {
                Some(PossibleValue::new("GFDL-1.1-no-invariants-only"))
            }
            Self::GFDL1x1UnoUinvariantsUorUlater => {
                Some(PossibleValue::new("GFDL-1.1-no-invariants-or-later"))
            }
            Self::GFDL1x1Uonly => Some(PossibleValue::new("GFDL-1.1-only")),
            Self::GFDL1x1UorUlater => Some(PossibleValue::new("GFDL-1.1-or-later")),
            Self::GFDL1x2UinvariantsUonly => Some(PossibleValue::new("GFDL-1.2-invariants-only")),
            Self::GFDL1x2UinvariantsUorUlater => {
                Some(PossibleValue::new("GFDL-1.2-invariants-or-later"))
            }
            Self::GFDL1x2UnoUinvariantsUonly => {
                Some(PossibleValue::new("GFDL-1.2-no-invariants-only"))
            }
            Self::GFDL1x2UnoUinvariantsUorUlater => {
                Some(PossibleValue::new("GFDL-1.2-no-invariants-or-later"))
            }
            Self::GFDL1x2Uonly => Some(PossibleValue::new("GFDL-1.2-only")),
            Self::GFDL1x2UorUlater => Some(PossibleValue::new("GFDL-1.2-or-later")),
            Self::GFDL1x3UinvariantsUonly => Some(PossibleValue::new("GFDL-1.3-invariants-only")),
            Self::GFDL1x3UinvariantsUorUlater => {
                Some(PossibleValue::new("GFDL-1.3-invariants-or-later"))
            }
            Self::GFDL1x3UnoUinvariantsUonly => {
                Some(PossibleValue::new("GFDL-1.3-no-invariants-only"))
            }
            Self::GFDL1x3UnoUinvariantsUorUlater => {
                Some(PossibleValue::new("GFDL-1.3-no-invariants-or-later"))
            }
            Self::GFDL1x3Uonly => Some(PossibleValue::new("GFDL-1.3-only")),
            Self::GFDL1x3UorUlater => Some(PossibleValue::new("GFDL-1.3-or-later")),
            Self::Giftware => Some(PossibleValue::new("Giftware")),
            Self::GL2PS => Some(PossibleValue::new("GL2PS")),
            Self::Glide => Some(PossibleValue::new("Glide")),
            Self::Glulxe => Some(PossibleValue::new("Glulxe")),
            Self::GLWTPL => Some(PossibleValue::new("GLWTPL")),
            Self::Gnuplot => Some(PossibleValue::new("gnuplot")),
            Self::GPL1x0Uonly => Some(PossibleValue::new("GPL-1.0-only")),
            Self::GPL1x0UorUlater => Some(PossibleValue::new("GPL-1.0-or-later")),
            Self::GPL2x0Uonly => Some(PossibleValue::new("GPL-2.0-only")),
            Self::GPL2x0UorUlater => Some(PossibleValue::new("GPL-2.0-or-later")),
            Self::GPL3x0Uonly => Some(PossibleValue::new("GPL-3.0-only")),
            Self::GPL3x0UorUlater => Some(PossibleValue::new("GPL-3.0-or-later")),
            Self::GraphicsUGems => Some(PossibleValue::new("Graphics-Gems")),
            Self::GSOAP1x3b => Some(PossibleValue::new("gSOAP-1.3b")),
            Self::Gtkbook => Some(PossibleValue::new("gtkbook")),
            Self::Gutmann => Some(PossibleValue::new("Gutmann")),
            Self::HaskellReport => Some(PossibleValue::new("HaskellReport")),
            Self::HDF5 => Some(PossibleValue::new("HDF5")),
            Self::Hdparm => Some(PossibleValue::new("hdparm")),
            Self::HIDAPI => Some(PossibleValue::new("HIDAPI")),
            Self::Hippocratic2x1 => Some(PossibleValue::new("Hippocratic-2.1")),
            Self::HP1986 => Some(PossibleValue::new("HP-1986")),
            Self::HP1989 => Some(PossibleValue::new("HP-1989")),
            Self::HPND => Some(PossibleValue::new("HPND")),
            Self::HPNDUDEC => Some(PossibleValue::new("HPND-DEC")),
            Self::HPNDUdoc => Some(PossibleValue::new("HPND-doc")),
            Self::HPNDUdocUsell => Some(PossibleValue::new("HPND-doc-sell")),
            Self::HPNDUexportUUS => Some(PossibleValue::new("HPND-export-US")),
            Self::HPNDUexportUUSUacknowledgement => {
                Some(PossibleValue::new("HPND-export-US-acknowledgement"))
            }
            Self::HPNDUexportUUSUmodify => Some(PossibleValue::new("HPND-export-US-modify")),
            Self::HPNDUexport2UUS => Some(PossibleValue::new("HPND-export2-US")),
            Self::HPNDUFennebergULivingston => {
                Some(PossibleValue::new("HPND-Fenneberg-Livingston"))
            }
            Self::HPNDUINRIAUIMAG => Some(PossibleValue::new("HPND-INRIA-IMAG")),
            Self::HPNDUIntel => Some(PossibleValue::new("HPND-Intel")),
            Self::HPNDUKevlinUHenney => Some(PossibleValue::new("HPND-Kevlin-Henney")),
            Self::HPNDUMarkusUKuhn => Some(PossibleValue::new("HPND-Markus-Kuhn")),
            Self::HPNDUmerchantabilityUvariant => {
                Some(PossibleValue::new("HPND-merchantability-variant"))
            }
            Self::HPNDUMITUdisclaimer => Some(PossibleValue::new("HPND-MIT-disclaimer")),
            Self::HPNDUNetrek => Some(PossibleValue::new("HPND-Netrek")),
            Self::HPNDUPbmplus => Some(PossibleValue::new("HPND-Pbmplus")),
            Self::HPNDUsellUMITUdisclaimerUxserver => {
                Some(PossibleValue::new("HPND-sell-MIT-disclaimer-xserver"))
            }
            Self::HPNDUsellUregexpr => Some(PossibleValue::new("HPND-sell-regexpr")),
            Self::HPNDUsellUvariant => Some(PossibleValue::new("HPND-sell-variant")),
            Self::HPNDUsellUvariantUcriticalUsystems => {
                Some(PossibleValue::new("HPND-sell-variant-critical-systems"))
            }
            Self::HPNDUsellUvariantUMITUdisclaimer => {
                Some(PossibleValue::new("HPND-sell-variant-MIT-disclaimer"))
            }
            Self::HPNDUsellUvariantUMITUdisclaimerUrev => {
                Some(PossibleValue::new("HPND-sell-variant-MIT-disclaimer-rev"))
            }
            Self::HPNDUSMC => Some(PossibleValue::new("HPND-SMC")),
            Self::HPNDUUC => Some(PossibleValue::new("HPND-UC")),
            Self::HPNDUUCUexportUUS => Some(PossibleValue::new("HPND-UC-export-US")),
            Self::HTMLTIDY => Some(PossibleValue::new("HTMLTIDY")),
            Self::HyphenUbulgarian => Some(PossibleValue::new("hyphen-bulgarian")),
            Self::IBMUpibs => Some(PossibleValue::new("IBM-pibs")),
            Self::ICU => Some(PossibleValue::new("ICU")),
            Self::IECUCodeUComponentsUEULA => Some(PossibleValue::new("IEC-Code-Components-EULA")),
            Self::IJG => Some(PossibleValue::new("IJG")),
            Self::IJGUshort => Some(PossibleValue::new("IJG-short")),
            Self::ImageMagick => Some(PossibleValue::new("ImageMagick")),
            Self::IMatix => Some(PossibleValue::new("iMatix")),
            Self::Imlib2 => Some(PossibleValue::new("Imlib2")),
            Self::InfoUZIP => Some(PossibleValue::new("Info-ZIP")),
            Self::InnerUNet2x0 => Some(PossibleValue::new("Inner-Net-2.0")),
            Self::InnoSetup => Some(PossibleValue::new("InnoSetup")),
            Self::Intel => Some(PossibleValue::new("Intel")),
            Self::IntelUACPI => Some(PossibleValue::new("Intel-ACPI")),
            Self::Interbase1x0 => Some(PossibleValue::new("Interbase-1.0")),
            Self::IPA => Some(PossibleValue::new("IPA")),
            Self::IPL1x0 => Some(PossibleValue::new("IPL-1.0")),
            Self::ISC => Some(PossibleValue::new("ISC")),
            Self::ISCUVeillard => Some(PossibleValue::new("ISC-Veillard")),
            Self::ISOUpermission => Some(PossibleValue::new("ISO-permission")),
            Self::Jam => Some(PossibleValue::new("Jam")),
            Self::JasPer2x0 => Some(PossibleValue::new("JasPer-2.0")),
            Self::Jove => Some(PossibleValue::new("jove")),
            Self::JPLUimage => Some(PossibleValue::new("JPL-image")),
            Self::JPNIC => Some(PossibleValue::new("JPNIC")),
            Self::JSON => Some(PossibleValue::new("JSON")),
            Self::Kastrup => Some(PossibleValue::new("Kastrup")),
            Self::Kazlib => Some(PossibleValue::new("Kazlib")),
            Self::KnuthUCTAN => Some(PossibleValue::new("Knuth-CTAN")),
            Self::LAL1x2 => Some(PossibleValue::new("LAL-1.2")),
            Self::LAL1x3 => Some(PossibleValue::new("LAL-1.3")),
            Self::Latex2e => Some(PossibleValue::new("Latex2e")),
            Self::Latex2eUtranslatedUnotice => {
                Some(PossibleValue::new("Latex2e-translated-notice"))
            }
            Self::Leptonica => Some(PossibleValue::new("Leptonica")),
            Self::LGPL2x0Uonly => Some(PossibleValue::new("LGPL-2.0-only")),
            Self::LGPL2x0UorUlater => Some(PossibleValue::new("LGPL-2.0-or-later")),
            Self::LGPL2x1Uonly => Some(PossibleValue::new("LGPL-2.1-only")),
            Self::LGPL2x1UorUlater => Some(PossibleValue::new("LGPL-2.1-or-later")),
            Self::LGPL3x0Uonly => Some(PossibleValue::new("LGPL-3.0-only")),
            Self::LGPL3x0UorUlater => Some(PossibleValue::new("LGPL-3.0-or-later")),
            Self::LGPLLR => Some(PossibleValue::new("LGPLLR")),
            Self::Libpng => Some(PossibleValue::new("Libpng")),
            Self::Libpng1x6x35 => Some(PossibleValue::new("libpng-1.6.35")),
            Self::Libpng2x0 => Some(PossibleValue::new("libpng-2.0")),
            Self::Libselinux1x0 => Some(PossibleValue::new("libselinux-1.0")),
            Self::Libtiff => Some(PossibleValue::new("libtiff")),
            Self::LibutilUDavidUNugent => Some(PossibleValue::new("libutil-David-Nugent")),
            Self::LiLiQUP1x1 => Some(PossibleValue::new("LiLiQ-P-1.1")),
            Self::LiLiQUR1x1 => Some(PossibleValue::new("LiLiQ-R-1.1")),
            Self::LiLiQURplus1x1 => Some(PossibleValue::new("LiLiQ-Rplus-1.1")),
            Self::LinuxUmanUpages1Upara => Some(PossibleValue::new("Linux-man-pages-1-para")),
            Self::LinuxUmanUpagesUcopyleft => Some(PossibleValue::new("Linux-man-pages-copyleft")),
            Self::LinuxUmanUpagesUcopyleft2Upara => {
                Some(PossibleValue::new("Linux-man-pages-copyleft-2-para"))
            }
            Self::LinuxUmanUpagesUcopyleftUvar => {
                Some(PossibleValue::new("Linux-man-pages-copyleft-var"))
            }
            Self::LinuxUOpenIB => Some(PossibleValue::new("Linux-OpenIB")),
            Self::LOOP => Some(PossibleValue::new("LOOP")),
            Self::LPDUdocument => Some(PossibleValue::new("LPD-document")),
            Self::LPL1x0 => Some(PossibleValue::new("LPL-1.0")),
            Self::LPL1x02 => Some(PossibleValue::new("LPL-1.02")),
            Self::LPPL1x0 => Some(PossibleValue::new("LPPL-1.0")),
            Self::LPPL1x1 => Some(PossibleValue::new("LPPL-1.1")),
            Self::LPPL1x2 => Some(PossibleValue::new("LPPL-1.2")),
            Self::LPPL1x3a => Some(PossibleValue::new("LPPL-1.3a")),
            Self::LPPL1x3c => Some(PossibleValue::new("LPPL-1.3c")),
            Self::Lsof => Some(PossibleValue::new("lsof")),
            Self::LucidaUBitmapUFonts => Some(PossibleValue::new("Lucida-Bitmap-Fonts")),
            Self::LZMAUSDK9x11Uto9x20 => Some(PossibleValue::new("LZMA-SDK-9.11-to-9.20")),
            Self::LZMAUSDK9x22 => Some(PossibleValue::new("LZMA-SDK-9.22")),
            Self::Mackerras3UClause => Some(PossibleValue::new("Mackerras-3-Clause")),
            Self::Mackerras3UClauseUacknowledgment => {
                Some(PossibleValue::new("Mackerras-3-Clause-acknowledgment"))
            }
            Self::Magaz => Some(PossibleValue::new("magaz")),
            Self::Mailprio => Some(PossibleValue::new("mailprio")),
            Self::MakeIndex => Some(PossibleValue::new("MakeIndex")),
            Self::Man2html => Some(PossibleValue::new("man2html")),
            Self::MartinUBirgmeier => Some(PossibleValue::new("Martin-Birgmeier")),
            Self::McPheeUslideshow => Some(PossibleValue::new("McPhee-slideshow")),
            Self::Metamail => Some(PossibleValue::new("metamail")),
            Self::Minpack => Some(PossibleValue::new("Minpack")),
            Self::MIPS => Some(PossibleValue::new("MIPS")),
            Self::MirOS => Some(PossibleValue::new("MirOS")),
            Self::MIT => Some(PossibleValue::new("MIT")),
            Self::MIT0 => Some(PossibleValue::new("MIT-0")),
            Self::MITUadvertising => Some(PossibleValue::new("MIT-advertising")),
            Self::MITUClick => Some(PossibleValue::new("MIT-Click")),
            Self::MITUCMU => Some(PossibleValue::new("MIT-CMU")),
            Self::MITUenna => Some(PossibleValue::new("MIT-enna")),
            Self::MITUfeh => Some(PossibleValue::new("MIT-feh")),
            Self::MITUFestival => Some(PossibleValue::new("MIT-Festival")),
            Self::MITUKhronosUold => Some(PossibleValue::new("MIT-Khronos-old")),
            Self::MITUModernUVariant => Some(PossibleValue::new("MIT-Modern-Variant")),
            Self::MITUopenUgroup => Some(PossibleValue::new("MIT-open-group")),
            Self::MITUSTK => Some(PossibleValue::new("MIT-STK")),
            Self::MITUtestregex => Some(PossibleValue::new("MIT-testregex")),
            Self::MITUWu => Some(PossibleValue::new("MIT-Wu")),
            Self::MITNFA => Some(PossibleValue::new("MITNFA")),
            Self::MMIXware => Some(PossibleValue::new("MMIXware")),
            Self::MMPL1x0x1 => Some(PossibleValue::new("MMPL-1.0.1")),
            Self::Motosoto => Some(PossibleValue::new("Motosoto")),
            Self::MPEGUSSG => Some(PossibleValue::new("MPEG-SSG")),
            Self::MpiUpermissive => Some(PossibleValue::new("mpi-permissive")),
            Self::Mpich2 => Some(PossibleValue::new("mpich2")),
            Self::MPL1x0 => Some(PossibleValue::new("MPL-1.0")),
            Self::MPL1x1 => Some(PossibleValue::new("MPL-1.1")),
            Self::MPL2x0 => Some(PossibleValue::new("MPL-2.0")),
            Self::MPL2x0UnoUcopyleftUexception => {
                Some(PossibleValue::new("MPL-2.0-no-copyleft-exception"))
            }
            Self::Mplus => Some(PossibleValue::new("mplus")),
            Self::MSULPL => Some(PossibleValue::new("MS-LPL")),
            Self::MSUPL => Some(PossibleValue::new("MS-PL")),
            Self::MSURL => Some(PossibleValue::new("MS-RL")),
            Self::MTLL => Some(PossibleValue::new("MTLL")),
            Self::MulanPSL1x0 => Some(PossibleValue::new("MulanPSL-1.0")),
            Self::MulanPSL2x0 => Some(PossibleValue::new("MulanPSL-2.0")),
            Self::Multics => Some(PossibleValue::new("Multics")),
            Self::Mup => Some(PossibleValue::new("Mup")),
            Self::NAIST2003 => Some(PossibleValue::new("NAIST-2003")),
            Self::NASA1x3 => Some(PossibleValue::new("NASA-1.3")),
            Self::Naumen => Some(PossibleValue::new("Naumen")),
            Self::NBPL1x0 => Some(PossibleValue::new("NBPL-1.0")),
            Self::NCBIUPD => Some(PossibleValue::new("NCBI-PD")),
            Self::NCGLUUK2x0 => Some(PossibleValue::new("NCGL-UK-2.0")),
            Self::NCL => Some(PossibleValue::new("NCL")),
            Self::NCSA => Some(PossibleValue::new("NCSA")),
            Self::NetCDF => Some(PossibleValue::new("NetCDF")),
            Self::Newsletr => Some(PossibleValue::new("Newsletr")),
            Self::NGPL => Some(PossibleValue::new("NGPL")),
            Self::Ngrep => Some(PossibleValue::new("ngrep")),
            Self::NICTA1x0 => Some(PossibleValue::new("NICTA-1.0")),
            Self::NISTUPD => Some(PossibleValue::new("NIST-PD")),
            Self::NISTUPDUfallback => Some(PossibleValue::new("NIST-PD-fallback")),
            Self::NISTUPDUTNT => Some(PossibleValue::new("NIST-PD-TNT")),
            Self::NISTUSoftware => Some(PossibleValue::new("NIST-Software")),
            Self::NLOD1x0 => Some(PossibleValue::new("NLOD-1.0")),
            Self::NLOD2x0 => Some(PossibleValue::new("NLOD-2.0")),
            Self::NLPL => Some(PossibleValue::new("NLPL")),
            Self::Nokia => Some(PossibleValue::new("Nokia")),
            Self::NOSL => Some(PossibleValue::new("NOSL")),
            Self::Noweb => Some(PossibleValue::new("Noweb")),
            Self::NPL1x0 => Some(PossibleValue::new("NPL-1.0")),
            Self::NPL1x1 => Some(PossibleValue::new("NPL-1.1")),
            Self::NPOSL3x0 => Some(PossibleValue::new("NPOSL-3.0")),
            Self::NRL => Some(PossibleValue::new("NRL")),
            Self::NTIAUPD => Some(PossibleValue::new("NTIA-PD")),
            Self::NTP => Some(PossibleValue::new("NTP")),
            Self::NTP0 => Some(PossibleValue::new("NTP-0")),
            Self::OUUDA1x0 => Some(PossibleValue::new("O-UDA-1.0")),
            Self::OAR => Some(PossibleValue::new("OAR")),
            Self::OCCTUPL => Some(PossibleValue::new("OCCT-PL")),
            Self::OCLC2x0 => Some(PossibleValue::new("OCLC-2.0")),
            Self::ODbL1x0 => Some(PossibleValue::new("ODbL-1.0")),
            Self::ODCUBy1x0 => Some(PossibleValue::new("ODC-By-1.0")),
            Self::OFFIS => Some(PossibleValue::new("OFFIS")),
            Self::OFL1x0 => Some(PossibleValue::new("OFL-1.0")),
            Self::OFL1x0UnoURFN => Some(PossibleValue::new("OFL-1.0-no-RFN")),
            Self::OFL1x0URFN => Some(PossibleValue::new("OFL-1.0-RFN")),
            Self::OFL1x1 => Some(PossibleValue::new("OFL-1.1")),
            Self::OFL1x1UnoURFN => Some(PossibleValue::new("OFL-1.1-no-RFN")),
            Self::OFL1x1URFN => Some(PossibleValue::new("OFL-1.1-RFN")),
            Self::OGC1x0 => Some(PossibleValue::new("OGC-1.0")),
            Self::OGDLUTaiwan1x0 => Some(PossibleValue::new("OGDL-Taiwan-1.0")),
            Self::OGLUCanada2x0 => Some(PossibleValue::new("OGL-Canada-2.0")),
            Self::OGLUUK1x0 => Some(PossibleValue::new("OGL-UK-1.0")),
            Self::OGLUUK2x0 => Some(PossibleValue::new("OGL-UK-2.0")),
            Self::OGLUUK3x0 => Some(PossibleValue::new("OGL-UK-3.0")),
            Self::OGTSL => Some(PossibleValue::new("OGTSL")),
            Self::OLDAP1x1 => Some(PossibleValue::new("OLDAP-1.1")),
            Self::OLDAP1x2 => Some(PossibleValue::new("OLDAP-1.2")),
            Self::OLDAP1x3 => Some(PossibleValue::new("OLDAP-1.3")),
            Self::OLDAP1x4 => Some(PossibleValue::new("OLDAP-1.4")),
            Self::OLDAP2x0 => Some(PossibleValue::new("OLDAP-2.0")),
            Self::OLDAP2x0x1 => Some(PossibleValue::new("OLDAP-2.0.1")),
            Self::OLDAP2x1 => Some(PossibleValue::new("OLDAP-2.1")),
            Self::OLDAP2x2 => Some(PossibleValue::new("OLDAP-2.2")),
            Self::OLDAP2x2x1 => Some(PossibleValue::new("OLDAP-2.2.1")),
            Self::OLDAP2x2x2 => Some(PossibleValue::new("OLDAP-2.2.2")),
            Self::OLDAP2x3 => Some(PossibleValue::new("OLDAP-2.3")),
            Self::OLDAP2x4 => Some(PossibleValue::new("OLDAP-2.4")),
            Self::OLDAP2x5 => Some(PossibleValue::new("OLDAP-2.5")),
            Self::OLDAP2x6 => Some(PossibleValue::new("OLDAP-2.6")),
            Self::OLDAP2x7 => Some(PossibleValue::new("OLDAP-2.7")),
            Self::OLDAP2x8 => Some(PossibleValue::new("OLDAP-2.8")),
            Self::OLFL1x3 => Some(PossibleValue::new("OLFL-1.3")),
            Self::OML => Some(PossibleValue::new("OML")),
            Self::OpenMDW1x0 => Some(PossibleValue::new("OpenMDW-1.0")),
            Self::OpenPBS2x3 => Some(PossibleValue::new("OpenPBS-2.3")),
            Self::OpenSSL => Some(PossibleValue::new("OpenSSL")),
            Self::OpenSSLUstandalone => Some(PossibleValue::new("OpenSSL-standalone")),
            Self::OpenVision => Some(PossibleValue::new("OpenVision")),
            Self::OPL1x0 => Some(PossibleValue::new("OPL-1.0")),
            Self::OPLUUK3x0 => Some(PossibleValue::new("OPL-UK-3.0")),
            Self::OPUBL1x0 => Some(PossibleValue::new("OPUBL-1.0")),
            Self::OSC1x0 => Some(PossibleValue::new("OSC-1.0")),
            Self::OSETUPL2x1 => Some(PossibleValue::new("OSET-PL-2.1")),
            Self::OSL1x0 => Some(PossibleValue::new("OSL-1.0")),
            Self::OSL1x1 => Some(PossibleValue::new("OSL-1.1")),
            Self::OSL2x0 => Some(PossibleValue::new("OSL-2.0")),
            Self::OSL2x1 => Some(PossibleValue::new("OSL-2.1")),
            Self::OSL3x0 => Some(PossibleValue::new("OSL-3.0")),
            Self::OSSP => Some(PossibleValue::new("OSSP")),
            Self::PADL => Some(PossibleValue::new("PADL")),
            Self::ParaTypeUFreeUFont1x3 => Some(PossibleValue::new("ParaType-Free-Font-1.3")),
            Self::Parity6x0x0 => Some(PossibleValue::new("Parity-6.0.0")),
            Self::Parity7x0x0 => Some(PossibleValue::new("Parity-7.0.0")),
            Self::PDDL1x0 => Some(PossibleValue::new("PDDL-1.0")),
            Self::PHP3x0 => Some(PossibleValue::new("PHP-3.0")),
            Self::PHP3x01 => Some(PossibleValue::new("PHP-3.01")),
            Self::Pixar => Some(PossibleValue::new("Pixar")),
            Self::Pkgconf => Some(PossibleValue::new("pkgconf")),
            Self::Plexus => Some(PossibleValue::new("Plexus")),
            Self::Pnmstitch => Some(PossibleValue::new("pnmstitch")),
            Self::PolyFormUNoncommercial1x0x0 => {
                Some(PossibleValue::new("PolyForm-Noncommercial-1.0.0"))
            }
            Self::PolyFormUSmallUBusiness1x0x0 => {
                Some(PossibleValue::new("PolyForm-Small-Business-1.0.0"))
            }
            Self::PostgreSQL => Some(PossibleValue::new("PostgreSQL")),
            Self::PPL => Some(PossibleValue::new("PPL")),
            Self::PSF2x0 => Some(PossibleValue::new("PSF-2.0")),
            Self::Psfrag => Some(PossibleValue::new("psfrag")),
            Self::Psutils => Some(PossibleValue::new("psutils")),
            Self::Python2x0 => Some(PossibleValue::new("Python-2.0")),
            Self::Python2x0x1 => Some(PossibleValue::new("Python-2.0.1")),
            Self::PythonUldap => Some(PossibleValue::new("python-ldap")),
            Self::Qhull => Some(PossibleValue::new("Qhull")),
            Self::QPL1x0 => Some(PossibleValue::new("QPL-1.0")),
            Self::QPL1x0UINRIA2004 => Some(PossibleValue::new("QPL-1.0-INRIA-2004")),
            Self::Radvd => Some(PossibleValue::new("radvd")),
            Self::Rdisc => Some(PossibleValue::new("Rdisc")),
            Self::RHeCos1x1 => Some(PossibleValue::new("RHeCos-1.1")),
            Self::RPL1x1 => Some(PossibleValue::new("RPL-1.1")),
            Self::RPL1x5 => Some(PossibleValue::new("RPL-1.5")),
            Self::RPSL1x0 => Some(PossibleValue::new("RPSL-1.0")),
            Self::RSAUMD => Some(PossibleValue::new("RSA-MD")),
            Self::RSCPL => Some(PossibleValue::new("RSCPL")),
            Self::Ruby => Some(PossibleValue::new("Ruby")),
            Self::RubyUpty => Some(PossibleValue::new("Ruby-pty")),
            Self::SAXUPD => Some(PossibleValue::new("SAX-PD")),
            Self::SAXUPD2x0 => Some(PossibleValue::new("SAX-PD-2.0")),
            Self::Saxpath => Some(PossibleValue::new("Saxpath")),
            Self::SCEA => Some(PossibleValue::new("SCEA")),
            Self::SchemeReport => Some(PossibleValue::new("SchemeReport")),
            Self::Sendmail => Some(PossibleValue::new("Sendmail")),
            Self::Sendmail8x23 => Some(PossibleValue::new("Sendmail-8.23")),
            Self::SendmailUOpenUSource1x1 => Some(PossibleValue::new("Sendmail-Open-Source-1.1")),
            Self::SGIUB1x0 => Some(PossibleValue::new("SGI-B-1.0")),
            Self::SGIUB1x1 => Some(PossibleValue::new("SGI-B-1.1")),
            Self::SGIUB2x0 => Some(PossibleValue::new("SGI-B-2.0")),
            Self::SGIUOpenGL => Some(PossibleValue::new("SGI-OpenGL")),
            Self::SGMLUGUPM => Some(PossibleValue::new("SGMLUG-PM")),
            Self::SGP4 => Some(PossibleValue::new("SGP4")),
            Self::SHL0x5 => Some(PossibleValue::new("SHL-0.5")),
            Self::SHL0x51 => Some(PossibleValue::new("SHL-0.51")),
            Self::SimPL2x0 => Some(PossibleValue::new("SimPL-2.0")),
            Self::SISSL => Some(PossibleValue::new("SISSL")),
            Self::SISSL1x2 => Some(PossibleValue::new("SISSL-1.2")),
            Self::SL => Some(PossibleValue::new("SL")),
            Self::Sleepycat => Some(PossibleValue::new("Sleepycat")),
            Self::SMAILUGPL => Some(PossibleValue::new("SMAIL-GPL")),
            Self::SMLNJ => Some(PossibleValue::new("SMLNJ")),
            Self::SMPPL => Some(PossibleValue::new("SMPPL")),
            Self::SNIA => Some(PossibleValue::new("SNIA")),
            Self::Snprintf => Some(PossibleValue::new("snprintf")),
            Self::SOFA => Some(PossibleValue::new("SOFA")),
            Self::SoftSurfer => Some(PossibleValue::new("softSurfer")),
            Self::Soundex => Some(PossibleValue::new("Soundex")),
            Self::Spencer86 => Some(PossibleValue::new("Spencer-86")),
            Self::Spencer94 => Some(PossibleValue::new("Spencer-94")),
            Self::Spencer99 => Some(PossibleValue::new("Spencer-99")),
            Self::SPL1x0 => Some(PossibleValue::new("SPL-1.0")),
            Self::SshUkeyscan => Some(PossibleValue::new("ssh-keyscan")),
            Self::SSHUOpenSSH => Some(PossibleValue::new("SSH-OpenSSH")),
            Self::SSHUshort => Some(PossibleValue::new("SSH-short")),
            Self::SSLeayUstandalone => Some(PossibleValue::new("SSLeay-standalone")),
            Self::SSPL1x0 => Some(PossibleValue::new("SSPL-1.0")),
            Self::SugarCRM1x1x3 => Some(PossibleValue::new("SugarCRM-1.1.3")),
            Self::SUL1x0 => Some(PossibleValue::new("SUL-1.0")),
            Self::SunUPPP => Some(PossibleValue::new("Sun-PPP")),
            Self::SunUPPP2000 => Some(PossibleValue::new("Sun-PPP-2000")),
            Self::SunPro => Some(PossibleValue::new("SunPro")),
            Self::SWL => Some(PossibleValue::new("SWL")),
            Self::Swrule => Some(PossibleValue::new("swrule")),
            Self::Symlinks => Some(PossibleValue::new("Symlinks")),
            Self::TAPRUOHL1x0 => Some(PossibleValue::new("TAPR-OHL-1.0")),
            Self::TCL => Some(PossibleValue::new("TCL")),
            Self::TCPUwrappers => Some(PossibleValue::new("TCP-wrappers")),
            Self::TekHVC => Some(PossibleValue::new("TekHVC")),
            Self::TermReadKey => Some(PossibleValue::new("TermReadKey")),
            Self::TGPPL1x0 => Some(PossibleValue::new("TGPPL-1.0")),
            Self::ThirdEye => Some(PossibleValue::new("ThirdEye")),
            Self::Threeparttable => Some(PossibleValue::new("threeparttable")),
            Self::TMate => Some(PossibleValue::new("TMate")),
            Self::TORQUE1x1 => Some(PossibleValue::new("TORQUE-1.1")),
            Self::TOSL => Some(PossibleValue::new("TOSL")),
            Self::TPDL => Some(PossibleValue::new("TPDL")),
            Self::TPL1x0 => Some(PossibleValue::new("TPL-1.0")),
            Self::TrustedQSL => Some(PossibleValue::new("TrustedQSL")),
            Self::TTWL => Some(PossibleValue::new("TTWL")),
            Self::TTYP0 => Some(PossibleValue::new("TTYP0")),
            Self::TUUBerlin1x0 => Some(PossibleValue::new("TU-Berlin-1.0")),
            Self::TUUBerlin2x0 => Some(PossibleValue::new("TU-Berlin-2.0")),
            Self::UbuntuUfont1x0 => Some(PossibleValue::new("Ubuntu-font-1.0")),
            Self::UCAR => Some(PossibleValue::new("UCAR")),
            Self::UCL1x0 => Some(PossibleValue::new("UCL-1.0")),
            Self::Ulem => Some(PossibleValue::new("ulem")),
            Self::UMichUMerit => Some(PossibleValue::new("UMich-Merit")),
            Self::Unicode3x0 => Some(PossibleValue::new("Unicode-3.0")),
            Self::UnicodeUDFS2015 => Some(PossibleValue::new("Unicode-DFS-2015")),
            Self::UnicodeUDFS2016 => Some(PossibleValue::new("Unicode-DFS-2016")),
            Self::UnicodeUTOU => Some(PossibleValue::new("Unicode-TOU")),
            Self::UnixCrypt => Some(PossibleValue::new("UnixCrypt")),
            Self::Unlicense => Some(PossibleValue::new("Unlicense")),
            Self::UnlicenseUlibtelnet => Some(PossibleValue::new("Unlicense-libtelnet")),
            Self::UnlicenseUlibwhirlpool => Some(PossibleValue::new("Unlicense-libwhirlpool")),
            Self::UnRAR => Some(PossibleValue::new("UnRAR")),
            Self::UPL1x0 => Some(PossibleValue::new("UPL-1.0")),
            Self::URTURLE => Some(PossibleValue::new("URT-RLE")),
            Self::Vim => Some(PossibleValue::new("Vim")),
            Self::VixieUCron => Some(PossibleValue::new("Vixie-Cron")),
            Self::VOSTROM => Some(PossibleValue::new("VOSTROM")),
            Self::VSL1x0 => Some(PossibleValue::new("VSL-1.0")),
            Self::W3C => Some(PossibleValue::new("W3C")),
            Self::W3C19980720 => Some(PossibleValue::new("W3C-19980720")),
            Self::W3C20150513 => Some(PossibleValue::new("W3C-20150513")),
            Self::W3m => Some(PossibleValue::new("w3m")),
            Self::Watcom1x0 => Some(PossibleValue::new("Watcom-1.0")),
            Self::WidgetUWorkshop => Some(PossibleValue::new("Widget-Workshop")),
            Self::WordNet => Some(PossibleValue::new("WordNet")),
            Self::Wsuipa => Some(PossibleValue::new("Wsuipa")),
            Self::WTFNMFPL => Some(PossibleValue::new("WTFNMFPL")),
            Self::WTFPL => Some(PossibleValue::new("WTFPL")),
            Self::Wwl => Some(PossibleValue::new("wwl")),
            Self::X11 => Some(PossibleValue::new("X11")),
            Self::X11UdistributeUmodificationsUvariant => {
                Some(PossibleValue::new("X11-distribute-modifications-variant"))
            }
            Self::X11UnoUpermitUpersons => Some(PossibleValue::new("X11-no-permit-persons")),
            Self::X11Uswapped => Some(PossibleValue::new("X11-swapped")),
            Self::Xdebug1x03 => Some(PossibleValue::new("Xdebug-1.03")),
            Self::Xerox => Some(PossibleValue::new("Xerox")),
            Self::Xfig => Some(PossibleValue::new("Xfig")),
            Self::XFree861x1 => Some(PossibleValue::new("XFree86-1.1")),
            Self::Xinetd => Some(PossibleValue::new("xinetd")),
            Self::XkeyboardUconfigUZinoviev => {
                Some(PossibleValue::new("xkeyboard-config-Zinoviev"))
            }
            Self::Xlock => Some(PossibleValue::new("xlock")),
            Self::Xnet => Some(PossibleValue::new("Xnet")),
            Self::Xpp => Some(PossibleValue::new("xpp")),
            Self::XSkat => Some(PossibleValue::new("XSkat")),
            Self::Xzoom => Some(PossibleValue::new("xzoom")),
            Self::YPL1x0 => Some(PossibleValue::new("YPL-1.0")),
            Self::YPL1x1 => Some(PossibleValue::new("YPL-1.1")),
            Self::Zed => Some(PossibleValue::new("Zed")),
            Self::Zeeff => Some(PossibleValue::new("Zeeff")),
            Self::Zend2x0 => Some(PossibleValue::new("Zend-2.0")),
            Self::Zimbra1x3 => Some(PossibleValue::new("Zimbra-1.3")),
            Self::Zimbra1x4 => Some(PossibleValue::new("Zimbra-1.4")),
            Self::Zlib => Some(PossibleValue::new("Zlib")),
            Self::ZlibUacknowledgement => Some(PossibleValue::new("zlib-acknowledgement")),
            Self::ZPL1x1 => Some(PossibleValue::new("ZPL-1.1")),
            Self::ZPL2x0 => Some(PossibleValue::new("ZPL-2.0")),
            Self::ZPL2x1 => Some(PossibleValue::new("ZPL-2.1")),
            Self::AGPL1x0 => Some(PossibleValue::new("AGPL-1.0")),
            Self::AGPL3x0 => Some(PossibleValue::new("AGPL-3.0")),
            Self::BSD2UClauseUFreeBSD => Some(PossibleValue::new("BSD-2-Clause-FreeBSD")),
            Self::BSD2UClauseUNetBSD => Some(PossibleValue::new("BSD-2-Clause-NetBSD")),
            Self::Bzip21x0x5 => Some(PossibleValue::new("bzip2-1.0.5")),
            Self::ECos2x0 => Some(PossibleValue::new("eCos-2.0")),
            Self::GFDL1x1 => Some(PossibleValue::new("GFDL-1.1")),
            Self::GFDL1x2 => Some(PossibleValue::new("GFDL-1.2")),
            Self::GFDL1x3 => Some(PossibleValue::new("GFDL-1.3")),
            Self::GPL1x0 => Some(PossibleValue::new("GPL-1.0")),
            Self::GPL1x0xPlus => Some(PossibleValue::new("GPL-1.0+")),
            Self::GPL2x0 => Some(PossibleValue::new("GPL-2.0")),
            Self::GPL2x0xPlus => Some(PossibleValue::new("GPL-2.0+")),
            Self::GPL2x0UwithUautoconfUexception => {
                Some(PossibleValue::new("GPL-2.0-with-autoconf-exception"))
            }
            Self::GPL2x0UwithUbisonUexception => {
                Some(PossibleValue::new("GPL-2.0-with-bison-exception"))
            }
            Self::GPL2x0UwithUclasspathUexception => {
                Some(PossibleValue::new("GPL-2.0-with-classpath-exception"))
            }
            Self::GPL2x0UwithUfontUexception => {
                Some(PossibleValue::new("GPL-2.0-with-font-exception"))
            }
            Self::GPL2x0UwithUGCCUexception => {
                Some(PossibleValue::new("GPL-2.0-with-GCC-exception"))
            }
            Self::GPL3x0 => Some(PossibleValue::new("GPL-3.0")),
            Self::GPL3x0xPlus => Some(PossibleValue::new("GPL-3.0+")),
            Self::GPL3x0UwithUautoconfUexception => {
                Some(PossibleValue::new("GPL-3.0-with-autoconf-exception"))
            }
            Self::GPL3x0UwithUGCCUexception => {
                Some(PossibleValue::new("GPL-3.0-with-GCC-exception"))
            }
            Self::LGPL2x0 => Some(PossibleValue::new("LGPL-2.0")),
            Self::LGPL2x0xPlus => Some(PossibleValue::new("LGPL-2.0+")),
            Self::LGPL2x1 => Some(PossibleValue::new("LGPL-2.1")),
            Self::LGPL2x1xPlus => Some(PossibleValue::new("LGPL-2.1+")),
            Self::LGPL3x0 => Some(PossibleValue::new("LGPL-3.0")),
            Self::LGPL3x0xPlus => Some(PossibleValue::new("LGPL-3.0+")),
            Self::NetUSNMP => Some(PossibleValue::new("Net-SNMP")),
            Self::Nunit => Some(PossibleValue::new("Nunit")),
            Self::StandardMLUNJ => Some(PossibleValue::new("StandardML-NJ")),
            Self::WxWindows => Some(PossibleValue::new("wxWindows")),
        }
    }

    fn value_variants<'a>() -> &'a [Self] {
        &[
            Self::_0BSD,
            Self::_3DUSlicer1x0,
            Self::AAL,
            Self::Abstyles,
            Self::AdaCoreUdoc,
            Self::Adobe2006,
            Self::AdobeUDisplayUPostScript,
            Self::AdobeUGlyph,
            Self::AdobeUUtopia,
            Self::ADSL,
            Self::AdvancedUCrypticsUDictionary,
            Self::AFL1x1,
            Self::AFL1x2,
            Self::AFL2x0,
            Self::AFL2x1,
            Self::AFL3x0,
            Self::Afmparse,
            Self::AGPL1x0Uonly,
            Self::AGPL1x0UorUlater,
            Self::AGPL3x0Uonly,
            Self::AGPL3x0UorUlater,
            Self::Aladdin,
            Self::ALGLIBUDocumentation,
            Self::AMDUnewlib,
            Self::AMDPLPA,
            Self::AML,
            Self::AMLUglslang,
            Self::AMPAS,
            Self::ANTLRUPD,
            Self::ANTLRUPDUfallback,
            Self::AnyUOSI,
            Self::AnyUOSIUperlUmodules,
            Self::Apache1x0,
            Self::Apache1x1,
            Self::Apache2x0,
            Self::APAFML,
            Self::APL1x0,
            Self::AppUs2p,
            Self::APSL1x0,
            Self::APSL1x1,
            Self::APSL1x2,
            Self::APSL2x0,
            Self::Arphic1999,
            Self::Artistic1x0,
            Self::Artistic1x0Ucl8,
            Self::Artistic1x0UPerl,
            Self::Artistic2x0,
            Self::ArtisticUdist,
            Self::AspellURU,
            Self::ASWFUDigitalUAssets1x0,
            Self::ASWFUDigitalUAssets1x1,
            Self::Baekmuk,
            Self::Bahyph,
            Self::Barr,
            Self::BcryptUSolarUDesigner,
            Self::Beerware,
            Self::BitstreamUCharter,
            Self::BitstreamUVera,
            Self::BitTorrent1x0,
            Self::BitTorrent1x1,
            Self::Blessing,
            Self::BlueOak1x0x0,
            Self::BoehmUGC,
            Self::BoehmUGCUwithoutUfee,
            Self::BOLA1x1,
            Self::Borceux,
            Self::BrianUGladman2UClause,
            Self::BrianUGladman3UClause,
            Self::BSD1UClause,
            Self::BSD2UClause,
            Self::BSD2UClauseUDarwin,
            Self::BSD2UClauseUfirstUlines,
            Self::BSD2UClauseUPatent,
            Self::BSD2UClauseUpkgconfUdisclaimer,
            Self::BSD2UClauseUViews,
            Self::BSD3UClause,
            Self::BSD3UClauseUacpica,
            Self::BSD3UClauseUAttribution,
            Self::BSD3UClauseUClear,
            Self::BSD3UClauseUflex,
            Self::BSD3UClauseUHP,
            Self::BSD3UClauseULBNL,
            Self::BSD3UClauseUModification,
            Self::BSD3UClauseUNoUMilitaryULicense,
            Self::BSD3UClauseUNoUNuclearULicense,
            Self::BSD3UClauseUNoUNuclearULicense2014,
            Self::BSD3UClauseUNoUNuclearUWarranty,
            Self::BSD3UClauseUOpenUMPI,
            Self::BSD3UClauseUSun,
            Self::BSD3UClauseUTso,
            Self::BSD4UClause,
            Self::BSD4UClauseUShortened,
            Self::BSD4UClauseUUC,
            Self::BSD4x3RENO,
            Self::BSD4x3TAHOE,
            Self::BSDUAdvertisingUAcknowledgement,
            Self::BSDUAttributionUHPNDUdisclaimer,
            Self::BSDUInfernoUNettverk,
            Self::BSDUMarkUModifications,
            Self::BSDUProtection,
            Self::BSDUSourceUbeginningUfile,
            Self::BSDUSourceUCode,
            Self::BSDUSystemics,
            Self::BSDUSystemicsUW3Works,
            Self::BSL1x0,
            Self::Buddy,
            Self::BUSL1x1,
            Self::Bzip21x0x6,
            Self::CUUDA1x0,
            Self::CAL1x0,
            Self::CAL1x0UCombinedUWorkUException,
            Self::Caldera,
            Self::CalderaUnoUpreamble,
            Self::CAPECUtou,
            Self::Catharon,
            Self::CATOSL1x1,
            Self::CCUBY1x0,
            Self::CCUBY2x0,
            Self::CCUBY2x5,
            Self::CCUBY2x5UAU,
            Self::CCUBY3x0,
            Self::CCUBY3x0UAT,
            Self::CCUBY3x0UAU,
            Self::CCUBY3x0UDE,
            Self::CCUBY3x0UIGO,
            Self::CCUBY3x0UNL,
            Self::CCUBY3x0UUS,
            Self::CCUBY4x0,
            Self::CCUBYUNC1x0,
            Self::CCUBYUNC2x0,
            Self::CCUBYUNC2x5,
            Self::CCUBYUNC3x0,
            Self::CCUBYUNC3x0UDE,
            Self::CCUBYUNC4x0,
            Self::CCUBYUNCUND1x0,
            Self::CCUBYUNCUND2x0,
            Self::CCUBYUNCUND2x5,
            Self::CCUBYUNCUND3x0,
            Self::CCUBYUNCUND3x0UDE,
            Self::CCUBYUNCUND3x0UIGO,
            Self::CCUBYUNCUND4x0,
            Self::CCUBYUNCUSA1x0,
            Self::CCUBYUNCUSA2x0,
            Self::CCUBYUNCUSA2x0UDE,
            Self::CCUBYUNCUSA2x0UFR,
            Self::CCUBYUNCUSA2x0UUK,
            Self::CCUBYUNCUSA2x5,
            Self::CCUBYUNCUSA3x0,
            Self::CCUBYUNCUSA3x0UDE,
            Self::CCUBYUNCUSA3x0UIGO,
            Self::CCUBYUNCUSA4x0,
            Self::CCUBYUND1x0,
            Self::CCUBYUND2x0,
            Self::CCUBYUND2x5,
            Self::CCUBYUND3x0,
            Self::CCUBYUND3x0UDE,
            Self::CCUBYUND4x0,
            Self::CCUBYUSA1x0,
            Self::CCUBYUSA2x0,
            Self::CCUBYUSA2x0UUK,
            Self::CCUBYUSA2x1UJP,
            Self::CCUBYUSA2x5,
            Self::CCUBYUSA3x0,
            Self::CCUBYUSA3x0UAT,
            Self::CCUBYUSA3x0UDE,
            Self::CCUBYUSA3x0UIGO,
            Self::CCUBYUSA4x0,
            Self::CCUPDDC,
            Self::CCUPDM1x0,
            Self::CCUSA1x0,
            Self::CC01x0,
            Self::CDDL1x0,
            Self::CDDL1x1,
            Self::CDL1x0,
            Self::CDLAUPermissive1x0,
            Self::CDLAUPermissive2x0,
            Self::CDLAUSharing1x0,
            Self::CECILL1x0,
            Self::CECILL1x1,
            Self::CECILL2x0,
            Self::CECILL2x1,
            Self::CECILLUB,
            Self::CECILLUC,
            Self::CERNUOHL1x1,
            Self::CERNUOHL1x2,
            Self::CERNUOHLUP2x0,
            Self::CERNUOHLUS2x0,
            Self::CERNUOHLUW2x0,
            Self::CFITSIO,
            Self::CheckUcvs,
            Self::Checkmk,
            Self::ClArtistic,
            Self::Clips,
            Self::CMUUMach,
            Self::CMUUMachUnodoc,
            Self::CNRIUJython,
            Self::CNRIUPython,
            Self::CNRIUPythonUGPLUCompatible,
            Self::COIL1x0,
            Self::CommunityUSpec1x0,
            Self::Condor1x1,
            Self::CopyleftUnext0x3x0,
            Self::CopyleftUnext0x3x1,
            Self::CornellULosslessUJPEG,
            Self::CPAL1x0,
            Self::CPL1x0,
            Self::CPOL1x02,
            Self::Cronyx,
            Self::Crossword,
            Self::CryptoSwift,
            Self::CrystalStacker,
            Self::CUAUOPL1x0,
            Self::Cube,
            Self::Curl,
            Self::CveUtou,
            Self::DUFSL1x0,
            Self::DEC3UClause,
            Self::Diffmark,
            Self::DLUDEUBY2x0,
            Self::DLUDEUZERO2x0,
            Self::DOC,
            Self::DocBookUDTD,
            Self::DocBookUSchema,
            Self::DocBookUStylesheet,
            Self::DocBookUXML,
            Self::Dotseqn,
            Self::DRL1x0,
            Self::DRL1x1,
            Self::DSDP,
            Self::Dtoa,
            Self::Dvipdfm,
            Self::ECL1x0,
            Self::ECL2x0,
            Self::EFL1x0,
            Self::EFL2x0,
            Self::EGenix,
            Self::Elastic2x0,
            Self::Entessa,
            Self::EPICS,
            Self::EPL1x0,
            Self::EPL2x0,
            Self::ErlPL1x1,
            Self::ESAUPLUpermissive2x4,
            Self::ESAUPLUstrongUcopyleft2x4,
            Self::ESAUPLUweakUcopyleft2x4,
            Self::Etalab2x0,
            Self::EUDatagrid,
            Self::EUPL1x0,
            Self::EUPL1x1,
            Self::EUPL1x2,
            Self::Eurosym,
            Self::Fair,
            Self::FBM,
            Self::FDKUAAC,
            Self::FergusonUTwofish,
            Self::Frameworx1x0,
            Self::FreeBSDUDOC,
            Self::FreeImage,
            Self::FSFAP,
            Self::FSFAPUnoUwarrantyUdisclaimer,
            Self::FSFUL,
            Self::FSFULLR,
            Self::FSFULLRSD,
            Self::FSFULLRWD,
            Self::FSL1x1UALv2,
            Self::FSL1x1UMIT,
            Self::FTL,
            Self::Furuseth,
            Self::Fwlw,
            Self::GameUProgrammingUGems,
            Self::GCRUdocs,
            Self::GD,
            Self::GenericUxts,
            Self::GFDL1x1UinvariantsUonly,
            Self::GFDL1x1UinvariantsUorUlater,
            Self::GFDL1x1UnoUinvariantsUonly,
            Self::GFDL1x1UnoUinvariantsUorUlater,
            Self::GFDL1x1Uonly,
            Self::GFDL1x1UorUlater,
            Self::GFDL1x2UinvariantsUonly,
            Self::GFDL1x2UinvariantsUorUlater,
            Self::GFDL1x2UnoUinvariantsUonly,
            Self::GFDL1x2UnoUinvariantsUorUlater,
            Self::GFDL1x2Uonly,
            Self::GFDL1x2UorUlater,
            Self::GFDL1x3UinvariantsUonly,
            Self::GFDL1x3UinvariantsUorUlater,
            Self::GFDL1x3UnoUinvariantsUonly,
            Self::GFDL1x3UnoUinvariantsUorUlater,
            Self::GFDL1x3Uonly,
            Self::GFDL1x3UorUlater,
            Self::Giftware,
            Self::GL2PS,
            Self::Glide,
            Self::Glulxe,
            Self::GLWTPL,
            Self::Gnuplot,
            Self::GPL1x0Uonly,
            Self::GPL1x0UorUlater,
            Self::GPL2x0Uonly,
            Self::GPL2x0UorUlater,
            Self::GPL3x0Uonly,
            Self::GPL3x0UorUlater,
            Self::GraphicsUGems,
            Self::GSOAP1x3b,
            Self::Gtkbook,
            Self::Gutmann,
            Self::HaskellReport,
            Self::HDF5,
            Self::Hdparm,
            Self::HIDAPI,
            Self::Hippocratic2x1,
            Self::HP1986,
            Self::HP1989,
            Self::HPND,
            Self::HPNDUDEC,
            Self::HPNDUdoc,
            Self::HPNDUdocUsell,
            Self::HPNDUexportUUS,
            Self::HPNDUexportUUSUacknowledgement,
            Self::HPNDUexportUUSUmodify,
            Self::HPNDUexport2UUS,
            Self::HPNDUFennebergULivingston,
            Self::HPNDUINRIAUIMAG,
            Self::HPNDUIntel,
            Self::HPNDUKevlinUHenney,
            Self::HPNDUMarkusUKuhn,
            Self::HPNDUmerchantabilityUvariant,
            Self::HPNDUMITUdisclaimer,
            Self::HPNDUNetrek,
            Self::HPNDUPbmplus,
            Self::HPNDUsellUMITUdisclaimerUxserver,
            Self::HPNDUsellUregexpr,
            Self::HPNDUsellUvariant,
            Self::HPNDUsellUvariantUcriticalUsystems,
            Self::HPNDUsellUvariantUMITUdisclaimer,
            Self::HPNDUsellUvariantUMITUdisclaimerUrev,
            Self::HPNDUSMC,
            Self::HPNDUUC,
            Self::HPNDUUCUexportUUS,
            Self::HTMLTIDY,
            Self::HyphenUbulgarian,
            Self::IBMUpibs,
            Self::ICU,
            Self::IECUCodeUComponentsUEULA,
            Self::IJG,
            Self::IJGUshort,
            Self::ImageMagick,
            Self::IMatix,
            Self::Imlib2,
            Self::InfoUZIP,
            Self::InnerUNet2x0,
            Self::InnoSetup,
            Self::Intel,
            Self::IntelUACPI,
            Self::Interbase1x0,
            Self::IPA,
            Self::IPL1x0,
            Self::ISC,
            Self::ISCUVeillard,
            Self::ISOUpermission,
            Self::Jam,
            Self::JasPer2x0,
            Self::Jove,
            Self::JPLUimage,
            Self::JPNIC,
            Self::JSON,
            Self::Kastrup,
            Self::Kazlib,
            Self::KnuthUCTAN,
            Self::LAL1x2,
            Self::LAL1x3,
            Self::Latex2e,
            Self::Latex2eUtranslatedUnotice,
            Self::Leptonica,
            Self::LGPL2x0Uonly,
            Self::LGPL2x0UorUlater,
            Self::LGPL2x1Uonly,
            Self::LGPL2x1UorUlater,
            Self::LGPL3x0Uonly,
            Self::LGPL3x0UorUlater,
            Self::LGPLLR,
            Self::Libpng,
            Self::Libpng1x6x35,
            Self::Libpng2x0,
            Self::Libselinux1x0,
            Self::Libtiff,
            Self::LibutilUDavidUNugent,
            Self::LiLiQUP1x1,
            Self::LiLiQUR1x1,
            Self::LiLiQURplus1x1,
            Self::LinuxUmanUpages1Upara,
            Self::LinuxUmanUpagesUcopyleft,
            Self::LinuxUmanUpagesUcopyleft2Upara,
            Self::LinuxUmanUpagesUcopyleftUvar,
            Self::LinuxUOpenIB,
            Self::LOOP,
            Self::LPDUdocument,
            Self::LPL1x0,
            Self::LPL1x02,
            Self::LPPL1x0,
            Self::LPPL1x1,
            Self::LPPL1x2,
            Self::LPPL1x3a,
            Self::LPPL1x3c,
            Self::Lsof,
            Self::LucidaUBitmapUFonts,
            Self::LZMAUSDK9x11Uto9x20,
            Self::LZMAUSDK9x22,
            Self::Mackerras3UClause,
            Self::Mackerras3UClauseUacknowledgment,
            Self::Magaz,
            Self::Mailprio,
            Self::MakeIndex,
            Self::Man2html,
            Self::MartinUBirgmeier,
            Self::McPheeUslideshow,
            Self::Metamail,
            Self::Minpack,
            Self::MIPS,
            Self::MirOS,
            Self::MIT,
            Self::MIT0,
            Self::MITUadvertising,
            Self::MITUClick,
            Self::MITUCMU,
            Self::MITUenna,
            Self::MITUfeh,
            Self::MITUFestival,
            Self::MITUKhronosUold,
            Self::MITUModernUVariant,
            Self::MITUopenUgroup,
            Self::MITUSTK,
            Self::MITUtestregex,
            Self::MITUWu,
            Self::MITNFA,
            Self::MMIXware,
            Self::MMPL1x0x1,
            Self::Motosoto,
            Self::MPEGUSSG,
            Self::MpiUpermissive,
            Self::Mpich2,
            Self::MPL1x0,
            Self::MPL1x1,
            Self::MPL2x0,
            Self::MPL2x0UnoUcopyleftUexception,
            Self::Mplus,
            Self::MSULPL,
            Self::MSUPL,
            Self::MSURL,
            Self::MTLL,
            Self::MulanPSL1x0,
            Self::MulanPSL2x0,
            Self::Multics,
            Self::Mup,
            Self::NAIST2003,
            Self::NASA1x3,
            Self::Naumen,
            Self::NBPL1x0,
            Self::NCBIUPD,
            Self::NCGLUUK2x0,
            Self::NCL,
            Self::NCSA,
            Self::NetCDF,
            Self::Newsletr,
            Self::NGPL,
            Self::Ngrep,
            Self::NICTA1x0,
            Self::NISTUPD,
            Self::NISTUPDUfallback,
            Self::NISTUPDUTNT,
            Self::NISTUSoftware,
            Self::NLOD1x0,
            Self::NLOD2x0,
            Self::NLPL,
            Self::Nokia,
            Self::NOSL,
            Self::Noweb,
            Self::NPL1x0,
            Self::NPL1x1,
            Self::NPOSL3x0,
            Self::NRL,
            Self::NTIAUPD,
            Self::NTP,
            Self::NTP0,
            Self::OUUDA1x0,
            Self::OAR,
            Self::OCCTUPL,
            Self::OCLC2x0,
            Self::ODbL1x0,
            Self::ODCUBy1x0,
            Self::OFFIS,
            Self::OFL1x0,
            Self::OFL1x0UnoURFN,
            Self::OFL1x0URFN,
            Self::OFL1x1,
            Self::OFL1x1UnoURFN,
            Self::OFL1x1URFN,
            Self::OGC1x0,
            Self::OGDLUTaiwan1x0,
            Self::OGLUCanada2x0,
            Self::OGLUUK1x0,
            Self::OGLUUK2x0,
            Self::OGLUUK3x0,
            Self::OGTSL,
            Self::OLDAP1x1,
            Self::OLDAP1x2,
            Self::OLDAP1x3,
            Self::OLDAP1x4,
            Self::OLDAP2x0,
            Self::OLDAP2x0x1,
            Self::OLDAP2x1,
            Self::OLDAP2x2,
            Self::OLDAP2x2x1,
            Self::OLDAP2x2x2,
            Self::OLDAP2x3,
            Self::OLDAP2x4,
            Self::OLDAP2x5,
            Self::OLDAP2x6,
            Self::OLDAP2x7,
            Self::OLDAP2x8,
            Self::OLFL1x3,
            Self::OML,
            Self::OpenMDW1x0,
            Self::OpenPBS2x3,
            Self::OpenSSL,
            Self::OpenSSLUstandalone,
            Self::OpenVision,
            Self::OPL1x0,
            Self::OPLUUK3x0,
            Self::OPUBL1x0,
            Self::OSC1x0,
            Self::OSETUPL2x1,
            Self::OSL1x0,
            Self::OSL1x1,
            Self::OSL2x0,
            Self::OSL2x1,
            Self::OSL3x0,
            Self::OSSP,
            Self::PADL,
            Self::ParaTypeUFreeUFont1x3,
            Self::Parity6x0x0,
            Self::Parity7x0x0,
            Self::PDDL1x0,
            Self::PHP3x0,
            Self::PHP3x01,
            Self::Pixar,
            Self::Pkgconf,
            Self::Plexus,
            Self::Pnmstitch,
            Self::PolyFormUNoncommercial1x0x0,
            Self::PolyFormUSmallUBusiness1x0x0,
            Self::PostgreSQL,
            Self::PPL,
            Self::PSF2x0,
            Self::Psfrag,
            Self::Psutils,
            Self::Python2x0,
            Self::Python2x0x1,
            Self::PythonUldap,
            Self::Qhull,
            Self::QPL1x0,
            Self::QPL1x0UINRIA2004,
            Self::Radvd,
            Self::Rdisc,
            Self::RHeCos1x1,
            Self::RPL1x1,
            Self::RPL1x5,
            Self::RPSL1x0,
            Self::RSAUMD,
            Self::RSCPL,
            Self::Ruby,
            Self::RubyUpty,
            Self::SAXUPD,
            Self::SAXUPD2x0,
            Self::Saxpath,
            Self::SCEA,
            Self::SchemeReport,
            Self::Sendmail,
            Self::Sendmail8x23,
            Self::SendmailUOpenUSource1x1,
            Self::SGIUB1x0,
            Self::SGIUB1x1,
            Self::SGIUB2x0,
            Self::SGIUOpenGL,
            Self::SGMLUGUPM,
            Self::SGP4,
            Self::SHL0x5,
            Self::SHL0x51,
            Self::SimPL2x0,
            Self::SISSL,
            Self::SISSL1x2,
            Self::SL,
            Self::Sleepycat,
            Self::SMAILUGPL,
            Self::SMLNJ,
            Self::SMPPL,
            Self::SNIA,
            Self::Snprintf,
            Self::SOFA,
            Self::SoftSurfer,
            Self::Soundex,
            Self::Spencer86,
            Self::Spencer94,
            Self::Spencer99,
            Self::SPL1x0,
            Self::SshUkeyscan,
            Self::SSHUOpenSSH,
            Self::SSHUshort,
            Self::SSLeayUstandalone,
            Self::SSPL1x0,
            Self::SugarCRM1x1x3,
            Self::SUL1x0,
            Self::SunUPPP,
            Self::SunUPPP2000,
            Self::SunPro,
            Self::SWL,
            Self::Swrule,
            Self::Symlinks,
            Self::TAPRUOHL1x0,
            Self::TCL,
            Self::TCPUwrappers,
            Self::TekHVC,
            Self::TermReadKey,
            Self::TGPPL1x0,
            Self::ThirdEye,
            Self::Threeparttable,
            Self::TMate,
            Self::TORQUE1x1,
            Self::TOSL,
            Self::TPDL,
            Self::TPL1x0,
            Self::TrustedQSL,
            Self::TTWL,
            Self::TTYP0,
            Self::TUUBerlin1x0,
            Self::TUUBerlin2x0,
            Self::UbuntuUfont1x0,
            Self::UCAR,
            Self::UCL1x0,
            Self::Ulem,
            Self::UMichUMerit,
            Self::Unicode3x0,
            Self::UnicodeUDFS2015,
            Self::UnicodeUDFS2016,
            Self::UnicodeUTOU,
            Self::UnixCrypt,
            Self::Unlicense,
            Self::UnlicenseUlibtelnet,
            Self::UnlicenseUlibwhirlpool,
            Self::UnRAR,
            Self::UPL1x0,
            Self::URTURLE,
            Self::Vim,
            Self::VixieUCron,
            Self::VOSTROM,
            Self::VSL1x0,
            Self::W3C,
            Self::W3C19980720,
            Self::W3C20150513,
            Self::W3m,
            Self::Watcom1x0,
            Self::WidgetUWorkshop,
            Self::WordNet,
            Self::Wsuipa,
            Self::WTFNMFPL,
            Self::WTFPL,
            Self::Wwl,
            Self::X11,
            Self::X11UdistributeUmodificationsUvariant,
            Self::X11UnoUpermitUpersons,
            Self::X11Uswapped,
            Self::Xdebug1x03,
            Self::Xerox,
            Self::Xfig,
            Self::XFree861x1,
            Self::Xinetd,
            Self::XkeyboardUconfigUZinoviev,
            Self::Xlock,
            Self::Xnet,
            Self::Xpp,
            Self::XSkat,
            Self::Xzoom,
            Self::YPL1x0,
            Self::YPL1x1,
            Self::Zed,
            Self::Zeeff,
            Self::Zend2x0,
            Self::Zimbra1x3,
            Self::Zimbra1x4,
            Self::Zlib,
            Self::ZlibUacknowledgement,
            Self::ZPL1x1,
            Self::ZPL2x0,
            Self::ZPL2x1,
            Self::AGPL1x0,
            Self::AGPL3x0,
            Self::BSD2UClauseUFreeBSD,
            Self::BSD2UClauseUNetBSD,
            Self::Bzip21x0x5,
            Self::ECos2x0,
            Self::GFDL1x1,
            Self::GFDL1x2,
            Self::GFDL1x3,
            Self::GPL1x0,
            Self::GPL1x0xPlus,
            Self::GPL2x0,
            Self::GPL2x0xPlus,
            Self::GPL2x0UwithUautoconfUexception,
            Self::GPL2x0UwithUbisonUexception,
            Self::GPL2x0UwithUclasspathUexception,
            Self::GPL2x0UwithUfontUexception,
            Self::GPL2x0UwithUGCCUexception,
            Self::GPL3x0,
            Self::GPL3x0xPlus,
            Self::GPL3x0UwithUautoconfUexception,
            Self::GPL3x0UwithUGCCUexception,
            Self::LGPL2x0,
            Self::LGPL2x0xPlus,
            Self::LGPL2x1,
            Self::LGPL2x1xPlus,
            Self::LGPL3x0,
            Self::LGPL3x0xPlus,
            Self::NetUSNMP,
            Self::Nunit,
            Self::StandardMLUNJ,
            Self::WxWindows,
        ]
    }
}
