mod license_3_28_0_2026_02_20;
pub use license_3_28_0_2026_02_20::LICENSE_3_28_0_2026_02_20;
mod license_0bsd;
pub use license_0bsd::LICENSE_0BSD;
mod license_3d_slicer_1_0;
pub use license_3d_slicer_1_0::LICENSE_3D_SLICER_1_0;
mod license_aal;
pub use license_aal::LICENSE_AAL;
mod license_abstyles;
pub use license_abstyles::LICENSE_ABSTYLES;
mod license_adacore_doc;
pub use license_adacore_doc::LICENSE_ADACORE_DOC;
mod license_adobe_2006;
pub use license_adobe_2006::LICENSE_ADOBE_2006;
mod license_adobe_display_postscript;
pub use license_adobe_display_postscript::LICENSE_ADOBE_DISPLAY_POSTSCRIPT;
mod license_adobe_glyph;
pub use license_adobe_glyph::LICENSE_ADOBE_GLYPH;
mod license_adobe_utopia;
pub use license_adobe_utopia::LICENSE_ADOBE_UTOPIA;
mod license_adsl;
pub use license_adsl::LICENSE_ADSL;
mod license_advanced_cryptics_dictionary;
pub use license_advanced_cryptics_dictionary::LICENSE_ADVANCED_CRYPTICS_DICTIONARY;
mod license_afl_1_1;
pub use license_afl_1_1::LICENSE_AFL_1_1;
mod license_afl_1_2;
pub use license_afl_1_2::LICENSE_AFL_1_2;
mod license_afl_2_0;
pub use license_afl_2_0::LICENSE_AFL_2_0;
mod license_afl_2_1;
pub use license_afl_2_1::LICENSE_AFL_2_1;
mod license_afl_3_0;
pub use license_afl_3_0::LICENSE_AFL_3_0;
mod license_afmparse;
pub use license_afmparse::LICENSE_AFMPARSE;
mod license_agpl_1_0_only;
pub use license_agpl_1_0_only::LICENSE_AGPL_1_0_ONLY;
mod license_agpl_1_0_or_later;
pub use license_agpl_1_0_or_later::LICENSE_AGPL_1_0_OR_LATER;
mod license_agpl_3_0_only;
pub use license_agpl_3_0_only::LICENSE_AGPL_3_0_ONLY;
mod license_agpl_3_0_or_later;
pub use license_agpl_3_0_or_later::LICENSE_AGPL_3_0_OR_LATER;
mod license_aladdin;
pub use license_aladdin::LICENSE_ALADDIN;
mod license_alglib_documentation;
pub use license_alglib_documentation::LICENSE_ALGLIB_DOCUMENTATION;
mod license_amd_newlib;
pub use license_amd_newlib::LICENSE_AMD_NEWLIB;
mod license_amdplpa;
pub use license_amdplpa::LICENSE_AMDPLPA;
mod license_aml;
pub use license_aml::LICENSE_AML;
mod license_aml_glslang;
pub use license_aml_glslang::LICENSE_AML_GLSLANG;
mod license_ampas;
pub use license_ampas::LICENSE_AMPAS;
mod license_antlr_pd;
pub use license_antlr_pd::LICENSE_ANTLR_PD;
mod license_antlr_pd_fallback;
pub use license_antlr_pd_fallback::LICENSE_ANTLR_PD_FALLBACK;
mod license_any_osi;
pub use license_any_osi::LICENSE_ANY_OSI;
mod license_any_osi_perl_modules;
pub use license_any_osi_perl_modules::LICENSE_ANY_OSI_PERL_MODULES;
mod license_apache_1_0;
pub use license_apache_1_0::LICENSE_APACHE_1_0;
mod license_apache_1_1;
pub use license_apache_1_1::LICENSE_APACHE_1_1;
mod license_apache_2_0;
pub use license_apache_2_0::LICENSE_APACHE_2_0;
mod license_apafml;
pub use license_apafml::LICENSE_APAFML;
mod license_apl_1_0;
pub use license_apl_1_0::LICENSE_APL_1_0;
mod license_app_s2p;
pub use license_app_s2p::LICENSE_APP_S2P;
mod license_apsl_1_0;
pub use license_apsl_1_0::LICENSE_APSL_1_0;
mod license_apsl_1_1;
pub use license_apsl_1_1::LICENSE_APSL_1_1;
mod license_apsl_1_2;
pub use license_apsl_1_2::LICENSE_APSL_1_2;
mod license_apsl_2_0;
pub use license_apsl_2_0::LICENSE_APSL_2_0;
mod license_arphic_1999;
pub use license_arphic_1999::LICENSE_ARPHIC_1999;
mod license_artistic_1_0;
pub use license_artistic_1_0::LICENSE_ARTISTIC_1_0;
mod license_artistic_1_0_cl8;
pub use license_artistic_1_0_cl8::LICENSE_ARTISTIC_1_0_CL8;
mod license_artistic_1_0_perl;
pub use license_artistic_1_0_perl::LICENSE_ARTISTIC_1_0_PERL;
mod license_artistic_2_0;
pub use license_artistic_2_0::LICENSE_ARTISTIC_2_0;
mod license_artistic_dist;
pub use license_artistic_dist::LICENSE_ARTISTIC_DIST;
mod license_aspell_ru;
pub use license_aspell_ru::LICENSE_ASPELL_RU;
mod license_aswf_digital_assets_1_0;
pub use license_aswf_digital_assets_1_0::LICENSE_ASWF_DIGITAL_ASSETS_1_0;
mod license_aswf_digital_assets_1_1;
pub use license_aswf_digital_assets_1_1::LICENSE_ASWF_DIGITAL_ASSETS_1_1;
mod license_baekmuk;
pub use license_baekmuk::LICENSE_BAEKMUK;
mod license_bahyph;
pub use license_bahyph::LICENSE_BAHYPH;
mod license_barr;
pub use license_barr::LICENSE_BARR;
mod license_bcrypt_solar_designer;
pub use license_bcrypt_solar_designer::LICENSE_BCRYPT_SOLAR_DESIGNER;
mod license_beerware;
pub use license_beerware::LICENSE_BEERWARE;
mod license_bitstream_charter;
pub use license_bitstream_charter::LICENSE_BITSTREAM_CHARTER;
mod license_bitstream_vera;
pub use license_bitstream_vera::LICENSE_BITSTREAM_VERA;
mod license_bittorrent_1_0;
pub use license_bittorrent_1_0::LICENSE_BITTORRENT_1_0;
mod license_bittorrent_1_1;
pub use license_bittorrent_1_1::LICENSE_BITTORRENT_1_1;
mod license_blessing;
pub use license_blessing::LICENSE_BLESSING;
mod license_blueoak_1_0_0;
pub use license_blueoak_1_0_0::LICENSE_BLUEOAK_1_0_0;
mod license_boehm_gc;
pub use license_boehm_gc::LICENSE_BOEHM_GC;
mod license_boehm_gc_without_fee;
pub use license_boehm_gc_without_fee::LICENSE_BOEHM_GC_WITHOUT_FEE;
mod license_bola_1_1;
pub use license_bola_1_1::LICENSE_BOLA_1_1;
mod license_borceux;
pub use license_borceux::LICENSE_BORCEUX;
mod license_brian_gladman_2_clause;
pub use license_brian_gladman_2_clause::LICENSE_BRIAN_GLADMAN_2_CLAUSE;
mod license_brian_gladman_3_clause;
pub use license_brian_gladman_3_clause::LICENSE_BRIAN_GLADMAN_3_CLAUSE;
mod license_bsd_1_clause;
pub use license_bsd_1_clause::LICENSE_BSD_1_CLAUSE;
mod license_bsd_2_clause;
pub use license_bsd_2_clause::LICENSE_BSD_2_CLAUSE;
mod license_bsd_2_clause_darwin;
pub use license_bsd_2_clause_darwin::LICENSE_BSD_2_CLAUSE_DARWIN;
mod license_bsd_2_clause_first_lines;
pub use license_bsd_2_clause_first_lines::LICENSE_BSD_2_CLAUSE_FIRST_LINES;
mod license_bsd_2_clause_patent;
pub use license_bsd_2_clause_patent::LICENSE_BSD_2_CLAUSE_PATENT;
mod license_bsd_2_clause_pkgconf_disclaimer;
pub use license_bsd_2_clause_pkgconf_disclaimer::LICENSE_BSD_2_CLAUSE_PKGCONF_DISCLAIMER;
mod license_bsd_2_clause_views;
pub use license_bsd_2_clause_views::LICENSE_BSD_2_CLAUSE_VIEWS;
mod license_bsd_3_clause;
pub use license_bsd_3_clause::LICENSE_BSD_3_CLAUSE;
mod license_bsd_3_clause_acpica;
pub use license_bsd_3_clause_acpica::LICENSE_BSD_3_CLAUSE_ACPICA;
mod license_bsd_3_clause_attribution;
pub use license_bsd_3_clause_attribution::LICENSE_BSD_3_CLAUSE_ATTRIBUTION;
mod license_bsd_3_clause_clear;
pub use license_bsd_3_clause_clear::LICENSE_BSD_3_CLAUSE_CLEAR;
mod license_bsd_3_clause_flex;
pub use license_bsd_3_clause_flex::LICENSE_BSD_3_CLAUSE_FLEX;
mod license_bsd_3_clause_hp;
pub use license_bsd_3_clause_hp::LICENSE_BSD_3_CLAUSE_HP;
mod license_bsd_3_clause_lbnl;
pub use license_bsd_3_clause_lbnl::LICENSE_BSD_3_CLAUSE_LBNL;
mod license_bsd_3_clause_modification;
pub use license_bsd_3_clause_modification::LICENSE_BSD_3_CLAUSE_MODIFICATION;
mod license_bsd_3_clause_no_military_license;
pub use license_bsd_3_clause_no_military_license::LICENSE_BSD_3_CLAUSE_NO_MILITARY_LICENSE;
mod license_bsd_3_clause_no_nuclear_license;
pub use license_bsd_3_clause_no_nuclear_license::LICENSE_BSD_3_CLAUSE_NO_NUCLEAR_LICENSE;
mod license_bsd_3_clause_no_nuclear_license_2014;
pub use license_bsd_3_clause_no_nuclear_license_2014::LICENSE_BSD_3_CLAUSE_NO_NUCLEAR_LICENSE_2014;
mod license_bsd_3_clause_no_nuclear_warranty;
pub use license_bsd_3_clause_no_nuclear_warranty::LICENSE_BSD_3_CLAUSE_NO_NUCLEAR_WARRANTY;
mod license_bsd_3_clause_open_mpi;
pub use license_bsd_3_clause_open_mpi::LICENSE_BSD_3_CLAUSE_OPEN_MPI;
mod license_bsd_3_clause_sun;
pub use license_bsd_3_clause_sun::LICENSE_BSD_3_CLAUSE_SUN;
mod license_bsd_3_clause_tso;
pub use license_bsd_3_clause_tso::LICENSE_BSD_3_CLAUSE_TSO;
mod license_bsd_4_clause;
pub use license_bsd_4_clause::LICENSE_BSD_4_CLAUSE;
mod license_bsd_4_clause_shortened;
pub use license_bsd_4_clause_shortened::LICENSE_BSD_4_CLAUSE_SHORTENED;
mod license_bsd_4_clause_uc;
pub use license_bsd_4_clause_uc::LICENSE_BSD_4_CLAUSE_UC;
mod license_bsd_4_3reno;
pub use license_bsd_4_3reno::LICENSE_BSD_4_3RENO;
mod license_bsd_4_3tahoe;
pub use license_bsd_4_3tahoe::LICENSE_BSD_4_3TAHOE;
mod license_bsd_advertising_acknowledgement;
pub use license_bsd_advertising_acknowledgement::LICENSE_BSD_ADVERTISING_ACKNOWLEDGEMENT;
mod license_bsd_attribution_hpnd_disclaimer;
pub use license_bsd_attribution_hpnd_disclaimer::LICENSE_BSD_ATTRIBUTION_HPND_DISCLAIMER;
mod license_bsd_inferno_nettverk;
pub use license_bsd_inferno_nettverk::LICENSE_BSD_INFERNO_NETTVERK;
mod license_bsd_mark_modifications;
pub use license_bsd_mark_modifications::LICENSE_BSD_MARK_MODIFICATIONS;
mod license_bsd_protection;
pub use license_bsd_protection::LICENSE_BSD_PROTECTION;
mod license_bsd_source_beginning_file;
pub use license_bsd_source_beginning_file::LICENSE_BSD_SOURCE_BEGINNING_FILE;
mod license_bsd_source_code;
pub use license_bsd_source_code::LICENSE_BSD_SOURCE_CODE;
mod license_bsd_systemics;
pub use license_bsd_systemics::LICENSE_BSD_SYSTEMICS;
mod license_bsd_systemics_w3works;
pub use license_bsd_systemics_w3works::LICENSE_BSD_SYSTEMICS_W3WORKS;
mod license_bsl_1_0;
pub use license_bsl_1_0::LICENSE_BSL_1_0;
mod license_buddy;
pub use license_buddy::LICENSE_BUDDY;
mod license_busl_1_1;
pub use license_busl_1_1::LICENSE_BUSL_1_1;
mod license_bzip2_1_0_6;
pub use license_bzip2_1_0_6::LICENSE_BZIP2_1_0_6;
mod license_c_uda_1_0;
pub use license_c_uda_1_0::LICENSE_C_UDA_1_0;
mod license_cal_1_0;
pub use license_cal_1_0::LICENSE_CAL_1_0;
mod license_cal_1_0_combined_work_exception;
pub use license_cal_1_0_combined_work_exception::LICENSE_CAL_1_0_COMBINED_WORK_EXCEPTION;
mod license_caldera;
pub use license_caldera::LICENSE_CALDERA;
mod license_caldera_no_preamble;
pub use license_caldera_no_preamble::LICENSE_CALDERA_NO_PREAMBLE;
mod license_capec_tou;
pub use license_capec_tou::LICENSE_CAPEC_TOU;
mod license_catharon;
pub use license_catharon::LICENSE_CATHARON;
mod license_catosl_1_1;
pub use license_catosl_1_1::LICENSE_CATOSL_1_1;
mod license_cc_by_1_0;
pub use license_cc_by_1_0::LICENSE_CC_BY_1_0;
mod license_cc_by_2_0;
pub use license_cc_by_2_0::LICENSE_CC_BY_2_0;
mod license_cc_by_2_5;
pub use license_cc_by_2_5::LICENSE_CC_BY_2_5;
mod license_cc_by_2_5_au;
pub use license_cc_by_2_5_au::LICENSE_CC_BY_2_5_AU;
mod license_cc_by_3_0;
pub use license_cc_by_3_0::LICENSE_CC_BY_3_0;
mod license_cc_by_3_0_at;
pub use license_cc_by_3_0_at::LICENSE_CC_BY_3_0_AT;
mod license_cc_by_3_0_au;
pub use license_cc_by_3_0_au::LICENSE_CC_BY_3_0_AU;
mod license_cc_by_3_0_de;
pub use license_cc_by_3_0_de::LICENSE_CC_BY_3_0_DE;
mod license_cc_by_3_0_igo;
pub use license_cc_by_3_0_igo::LICENSE_CC_BY_3_0_IGO;
mod license_cc_by_3_0_nl;
pub use license_cc_by_3_0_nl::LICENSE_CC_BY_3_0_NL;
mod license_cc_by_3_0_us;
pub use license_cc_by_3_0_us::LICENSE_CC_BY_3_0_US;
mod license_cc_by_4_0;
pub use license_cc_by_4_0::LICENSE_CC_BY_4_0;
mod license_cc_by_nc_1_0;
pub use license_cc_by_nc_1_0::LICENSE_CC_BY_NC_1_0;
mod license_cc_by_nc_2_0;
pub use license_cc_by_nc_2_0::LICENSE_CC_BY_NC_2_0;
mod license_cc_by_nc_2_5;
pub use license_cc_by_nc_2_5::LICENSE_CC_BY_NC_2_5;
mod license_cc_by_nc_3_0;
pub use license_cc_by_nc_3_0::LICENSE_CC_BY_NC_3_0;
mod license_cc_by_nc_3_0_de;
pub use license_cc_by_nc_3_0_de::LICENSE_CC_BY_NC_3_0_DE;
mod license_cc_by_nc_4_0;
pub use license_cc_by_nc_4_0::LICENSE_CC_BY_NC_4_0;
mod license_cc_by_nc_nd_1_0;
pub use license_cc_by_nc_nd_1_0::LICENSE_CC_BY_NC_ND_1_0;
mod license_cc_by_nc_nd_2_0;
pub use license_cc_by_nc_nd_2_0::LICENSE_CC_BY_NC_ND_2_0;
mod license_cc_by_nc_nd_2_5;
pub use license_cc_by_nc_nd_2_5::LICENSE_CC_BY_NC_ND_2_5;
mod license_cc_by_nc_nd_3_0;
pub use license_cc_by_nc_nd_3_0::LICENSE_CC_BY_NC_ND_3_0;
mod license_cc_by_nc_nd_3_0_de;
pub use license_cc_by_nc_nd_3_0_de::LICENSE_CC_BY_NC_ND_3_0_DE;
mod license_cc_by_nc_nd_3_0_igo;
pub use license_cc_by_nc_nd_3_0_igo::LICENSE_CC_BY_NC_ND_3_0_IGO;
mod license_cc_by_nc_nd_4_0;
pub use license_cc_by_nc_nd_4_0::LICENSE_CC_BY_NC_ND_4_0;
mod license_cc_by_nc_sa_1_0;
pub use license_cc_by_nc_sa_1_0::LICENSE_CC_BY_NC_SA_1_0;
mod license_cc_by_nc_sa_2_0;
pub use license_cc_by_nc_sa_2_0::LICENSE_CC_BY_NC_SA_2_0;
mod license_cc_by_nc_sa_2_0_de;
pub use license_cc_by_nc_sa_2_0_de::LICENSE_CC_BY_NC_SA_2_0_DE;
mod license_cc_by_nc_sa_2_0_fr;
pub use license_cc_by_nc_sa_2_0_fr::LICENSE_CC_BY_NC_SA_2_0_FR;
mod license_cc_by_nc_sa_2_0_uk;
pub use license_cc_by_nc_sa_2_0_uk::LICENSE_CC_BY_NC_SA_2_0_UK;
mod license_cc_by_nc_sa_2_5;
pub use license_cc_by_nc_sa_2_5::LICENSE_CC_BY_NC_SA_2_5;
mod license_cc_by_nc_sa_3_0;
pub use license_cc_by_nc_sa_3_0::LICENSE_CC_BY_NC_SA_3_0;
mod license_cc_by_nc_sa_3_0_de;
pub use license_cc_by_nc_sa_3_0_de::LICENSE_CC_BY_NC_SA_3_0_DE;
mod license_cc_by_nc_sa_3_0_igo;
pub use license_cc_by_nc_sa_3_0_igo::LICENSE_CC_BY_NC_SA_3_0_IGO;
mod license_cc_by_nc_sa_4_0;
pub use license_cc_by_nc_sa_4_0::LICENSE_CC_BY_NC_SA_4_0;
mod license_cc_by_nd_1_0;
pub use license_cc_by_nd_1_0::LICENSE_CC_BY_ND_1_0;
mod license_cc_by_nd_2_0;
pub use license_cc_by_nd_2_0::LICENSE_CC_BY_ND_2_0;
mod license_cc_by_nd_2_5;
pub use license_cc_by_nd_2_5::LICENSE_CC_BY_ND_2_5;
mod license_cc_by_nd_3_0;
pub use license_cc_by_nd_3_0::LICENSE_CC_BY_ND_3_0;
mod license_cc_by_nd_3_0_de;
pub use license_cc_by_nd_3_0_de::LICENSE_CC_BY_ND_3_0_DE;
mod license_cc_by_nd_4_0;
pub use license_cc_by_nd_4_0::LICENSE_CC_BY_ND_4_0;
mod license_cc_by_sa_1_0;
pub use license_cc_by_sa_1_0::LICENSE_CC_BY_SA_1_0;
mod license_cc_by_sa_2_0;
pub use license_cc_by_sa_2_0::LICENSE_CC_BY_SA_2_0;
mod license_cc_by_sa_2_0_uk;
pub use license_cc_by_sa_2_0_uk::LICENSE_CC_BY_SA_2_0_UK;
mod license_cc_by_sa_2_1_jp;
pub use license_cc_by_sa_2_1_jp::LICENSE_CC_BY_SA_2_1_JP;
mod license_cc_by_sa_2_5;
pub use license_cc_by_sa_2_5::LICENSE_CC_BY_SA_2_5;
mod license_cc_by_sa_3_0;
pub use license_cc_by_sa_3_0::LICENSE_CC_BY_SA_3_0;
mod license_cc_by_sa_3_0_at;
pub use license_cc_by_sa_3_0_at::LICENSE_CC_BY_SA_3_0_AT;
mod license_cc_by_sa_3_0_de;
pub use license_cc_by_sa_3_0_de::LICENSE_CC_BY_SA_3_0_DE;
mod license_cc_by_sa_3_0_igo;
pub use license_cc_by_sa_3_0_igo::LICENSE_CC_BY_SA_3_0_IGO;
mod license_cc_by_sa_4_0;
pub use license_cc_by_sa_4_0::LICENSE_CC_BY_SA_4_0;
mod license_cc_pddc;
pub use license_cc_pddc::LICENSE_CC_PDDC;
mod license_cc_pdm_1_0;
pub use license_cc_pdm_1_0::LICENSE_CC_PDM_1_0;
mod license_cc_sa_1_0;
pub use license_cc_sa_1_0::LICENSE_CC_SA_1_0;
mod license_cc0_1_0;
pub use license_cc0_1_0::LICENSE_CC0_1_0;
mod license_cddl_1_0;
pub use license_cddl_1_0::LICENSE_CDDL_1_0;
mod license_cddl_1_1;
pub use license_cddl_1_1::LICENSE_CDDL_1_1;
mod license_cdl_1_0;
pub use license_cdl_1_0::LICENSE_CDL_1_0;
mod license_cdla_permissive_1_0;
pub use license_cdla_permissive_1_0::LICENSE_CDLA_PERMISSIVE_1_0;
mod license_cdla_permissive_2_0;
pub use license_cdla_permissive_2_0::LICENSE_CDLA_PERMISSIVE_2_0;
mod license_cdla_sharing_1_0;
pub use license_cdla_sharing_1_0::LICENSE_CDLA_SHARING_1_0;
mod license_cecill_1_0;
pub use license_cecill_1_0::LICENSE_CECILL_1_0;
mod license_cecill_1_1;
pub use license_cecill_1_1::LICENSE_CECILL_1_1;
mod license_cecill_2_0;
pub use license_cecill_2_0::LICENSE_CECILL_2_0;
mod license_cecill_2_1;
pub use license_cecill_2_1::LICENSE_CECILL_2_1;
mod license_cecill_b;
pub use license_cecill_b::LICENSE_CECILL_B;
mod license_cecill_c;
pub use license_cecill_c::LICENSE_CECILL_C;
mod license_cern_ohl_1_1;
pub use license_cern_ohl_1_1::LICENSE_CERN_OHL_1_1;
mod license_cern_ohl_1_2;
pub use license_cern_ohl_1_2::LICENSE_CERN_OHL_1_2;
mod license_cern_ohl_p_2_0;
pub use license_cern_ohl_p_2_0::LICENSE_CERN_OHL_P_2_0;
mod license_cern_ohl_s_2_0;
pub use license_cern_ohl_s_2_0::LICENSE_CERN_OHL_S_2_0;
mod license_cern_ohl_w_2_0;
pub use license_cern_ohl_w_2_0::LICENSE_CERN_OHL_W_2_0;
mod license_cfitsio;
pub use license_cfitsio::LICENSE_CFITSIO;
mod license_check_cvs;
pub use license_check_cvs::LICENSE_CHECK_CVS;
mod license_checkmk;
pub use license_checkmk::LICENSE_CHECKMK;
mod license_clartistic;
pub use license_clartistic::LICENSE_CLARTISTIC;
mod license_clips;
pub use license_clips::LICENSE_CLIPS;
mod license_cmu_mach;
pub use license_cmu_mach::LICENSE_CMU_MACH;
mod license_cmu_mach_nodoc;
pub use license_cmu_mach_nodoc::LICENSE_CMU_MACH_NODOC;
mod license_cnri_jython;
pub use license_cnri_jython::LICENSE_CNRI_JYTHON;
mod license_cnri_python;
pub use license_cnri_python::LICENSE_CNRI_PYTHON;
mod license_cnri_python_gpl_compatible;
pub use license_cnri_python_gpl_compatible::LICENSE_CNRI_PYTHON_GPL_COMPATIBLE;
mod license_coil_1_0;
pub use license_coil_1_0::LICENSE_COIL_1_0;
mod license_community_spec_1_0;
pub use license_community_spec_1_0::LICENSE_COMMUNITY_SPEC_1_0;
mod license_condor_1_1;
pub use license_condor_1_1::LICENSE_CONDOR_1_1;
mod license_copyleft_next_0_3_0;
pub use license_copyleft_next_0_3_0::LICENSE_COPYLEFT_NEXT_0_3_0;
mod license_copyleft_next_0_3_1;
pub use license_copyleft_next_0_3_1::LICENSE_COPYLEFT_NEXT_0_3_1;
mod license_cornell_lossless_jpeg;
pub use license_cornell_lossless_jpeg::LICENSE_CORNELL_LOSSLESS_JPEG;
mod license_cpal_1_0;
pub use license_cpal_1_0::LICENSE_CPAL_1_0;
mod license_cpl_1_0;
pub use license_cpl_1_0::LICENSE_CPL_1_0;
mod license_cpol_1_02;
pub use license_cpol_1_02::LICENSE_CPOL_1_02;
mod license_cronyx;
pub use license_cronyx::LICENSE_CRONYX;
mod license_crossword;
pub use license_crossword::LICENSE_CROSSWORD;
mod license_cryptoswift;
pub use license_cryptoswift::LICENSE_CRYPTOSWIFT;
mod license_crystalstacker;
pub use license_crystalstacker::LICENSE_CRYSTALSTACKER;
mod license_cua_opl_1_0;
pub use license_cua_opl_1_0::LICENSE_CUA_OPL_1_0;
mod license_cube;
pub use license_cube::LICENSE_CUBE;
mod license_curl;
pub use license_curl::LICENSE_CURL;
mod license_cve_tou;
pub use license_cve_tou::LICENSE_CVE_TOU;
mod license_d_fsl_1_0;
pub use license_d_fsl_1_0::LICENSE_D_FSL_1_0;
mod license_dec_3_clause;
pub use license_dec_3_clause::LICENSE_DEC_3_CLAUSE;
mod license_diffmark;
pub use license_diffmark::LICENSE_DIFFMARK;
mod license_dl_de_by_2_0;
pub use license_dl_de_by_2_0::LICENSE_DL_DE_BY_2_0;
mod license_dl_de_zero_2_0;
pub use license_dl_de_zero_2_0::LICENSE_DL_DE_ZERO_2_0;
mod license_doc;
pub use license_doc::LICENSE_DOC;
mod license_docbook_dtd;
pub use license_docbook_dtd::LICENSE_DOCBOOK_DTD;
mod license_docbook_schema;
pub use license_docbook_schema::LICENSE_DOCBOOK_SCHEMA;
mod license_docbook_stylesheet;
pub use license_docbook_stylesheet::LICENSE_DOCBOOK_STYLESHEET;
mod license_docbook_xml;
pub use license_docbook_xml::LICENSE_DOCBOOK_XML;
mod license_dotseqn;
pub use license_dotseqn::LICENSE_DOTSEQN;
mod license_drl_1_0;
pub use license_drl_1_0::LICENSE_DRL_1_0;
mod license_drl_1_1;
pub use license_drl_1_1::LICENSE_DRL_1_1;
mod license_dsdp;
pub use license_dsdp::LICENSE_DSDP;
mod license_dtoa;
pub use license_dtoa::LICENSE_DTOA;
mod license_dvipdfm;
pub use license_dvipdfm::LICENSE_DVIPDFM;
mod license_ecl_1_0;
pub use license_ecl_1_0::LICENSE_ECL_1_0;
mod license_ecl_2_0;
pub use license_ecl_2_0::LICENSE_ECL_2_0;
mod license_efl_1_0;
pub use license_efl_1_0::LICENSE_EFL_1_0;
mod license_efl_2_0;
pub use license_efl_2_0::LICENSE_EFL_2_0;
mod license_egenix;
pub use license_egenix::LICENSE_EGENIX;
mod license_elastic_2_0;
pub use license_elastic_2_0::LICENSE_ELASTIC_2_0;
mod license_entessa;
pub use license_entessa::LICENSE_ENTESSA;
mod license_epics;
pub use license_epics::LICENSE_EPICS;
mod license_epl_1_0;
pub use license_epl_1_0::LICENSE_EPL_1_0;
mod license_epl_2_0;
pub use license_epl_2_0::LICENSE_EPL_2_0;
mod license_erlpl_1_1;
pub use license_erlpl_1_1::LICENSE_ERLPL_1_1;
mod license_esa_pl_permissive_2_4;
pub use license_esa_pl_permissive_2_4::LICENSE_ESA_PL_PERMISSIVE_2_4;
mod license_esa_pl_strong_copyleft_2_4;
pub use license_esa_pl_strong_copyleft_2_4::LICENSE_ESA_PL_STRONG_COPYLEFT_2_4;
mod license_esa_pl_weak_copyleft_2_4;
pub use license_esa_pl_weak_copyleft_2_4::LICENSE_ESA_PL_WEAK_COPYLEFT_2_4;
mod license_etalab_2_0;
pub use license_etalab_2_0::LICENSE_ETALAB_2_0;
mod license_eudatagrid;
pub use license_eudatagrid::LICENSE_EUDATAGRID;
mod license_eupl_1_0;
pub use license_eupl_1_0::LICENSE_EUPL_1_0;
mod license_eupl_1_1;
pub use license_eupl_1_1::LICENSE_EUPL_1_1;
mod license_eupl_1_2;
pub use license_eupl_1_2::LICENSE_EUPL_1_2;
mod license_eurosym;
pub use license_eurosym::LICENSE_EUROSYM;
mod license_fair;
pub use license_fair::LICENSE_FAIR;
mod license_fbm;
pub use license_fbm::LICENSE_FBM;
mod license_fdk_aac;
pub use license_fdk_aac::LICENSE_FDK_AAC;
mod license_ferguson_twofish;
pub use license_ferguson_twofish::LICENSE_FERGUSON_TWOFISH;
mod license_frameworx_1_0;
pub use license_frameworx_1_0::LICENSE_FRAMEWORX_1_0;
mod license_freebsd_doc;
pub use license_freebsd_doc::LICENSE_FREEBSD_DOC;
mod license_freeimage;
pub use license_freeimage::LICENSE_FREEIMAGE;
mod license_fsfap;
pub use license_fsfap::LICENSE_FSFAP;
mod license_fsfap_no_warranty_disclaimer;
pub use license_fsfap_no_warranty_disclaimer::LICENSE_FSFAP_NO_WARRANTY_DISCLAIMER;
mod license_fsful;
pub use license_fsful::LICENSE_FSFUL;
mod license_fsfullr;
pub use license_fsfullr::LICENSE_FSFULLR;
mod license_fsfullrsd;
pub use license_fsfullrsd::LICENSE_FSFULLRSD;
mod license_fsfullrwd;
pub use license_fsfullrwd::LICENSE_FSFULLRWD;
mod license_fsl_1_1_alv2;
pub use license_fsl_1_1_alv2::LICENSE_FSL_1_1_ALV2;
mod license_fsl_1_1_mit;
pub use license_fsl_1_1_mit::LICENSE_FSL_1_1_MIT;
mod license_ftl;
pub use license_ftl::LICENSE_FTL;
mod license_furuseth;
pub use license_furuseth::LICENSE_FURUSETH;
mod license_fwlw;
pub use license_fwlw::LICENSE_FWLW;
mod license_game_programming_gems;
pub use license_game_programming_gems::LICENSE_GAME_PROGRAMMING_GEMS;
mod license_gcr_docs;
pub use license_gcr_docs::LICENSE_GCR_DOCS;
mod license_gd;
pub use license_gd::LICENSE_GD;
mod license_generic_xts;
pub use license_generic_xts::LICENSE_GENERIC_XTS;
mod license_gfdl_1_1_invariants_only;
pub use license_gfdl_1_1_invariants_only::LICENSE_GFDL_1_1_INVARIANTS_ONLY;
mod license_gfdl_1_1_invariants_or_later;
pub use license_gfdl_1_1_invariants_or_later::LICENSE_GFDL_1_1_INVARIANTS_OR_LATER;
mod license_gfdl_1_1_no_invariants_only;
pub use license_gfdl_1_1_no_invariants_only::LICENSE_GFDL_1_1_NO_INVARIANTS_ONLY;
mod license_gfdl_1_1_no_invariants_or_later;
pub use license_gfdl_1_1_no_invariants_or_later::LICENSE_GFDL_1_1_NO_INVARIANTS_OR_LATER;
mod license_gfdl_1_1_only;
pub use license_gfdl_1_1_only::LICENSE_GFDL_1_1_ONLY;
mod license_gfdl_1_1_or_later;
pub use license_gfdl_1_1_or_later::LICENSE_GFDL_1_1_OR_LATER;
mod license_gfdl_1_2_invariants_only;
pub use license_gfdl_1_2_invariants_only::LICENSE_GFDL_1_2_INVARIANTS_ONLY;
mod license_gfdl_1_2_invariants_or_later;
pub use license_gfdl_1_2_invariants_or_later::LICENSE_GFDL_1_2_INVARIANTS_OR_LATER;
mod license_gfdl_1_2_no_invariants_only;
pub use license_gfdl_1_2_no_invariants_only::LICENSE_GFDL_1_2_NO_INVARIANTS_ONLY;
mod license_gfdl_1_2_no_invariants_or_later;
pub use license_gfdl_1_2_no_invariants_or_later::LICENSE_GFDL_1_2_NO_INVARIANTS_OR_LATER;
mod license_gfdl_1_2_only;
pub use license_gfdl_1_2_only::LICENSE_GFDL_1_2_ONLY;
mod license_gfdl_1_2_or_later;
pub use license_gfdl_1_2_or_later::LICENSE_GFDL_1_2_OR_LATER;
mod license_gfdl_1_3_invariants_only;
pub use license_gfdl_1_3_invariants_only::LICENSE_GFDL_1_3_INVARIANTS_ONLY;
mod license_gfdl_1_3_invariants_or_later;
pub use license_gfdl_1_3_invariants_or_later::LICENSE_GFDL_1_3_INVARIANTS_OR_LATER;
mod license_gfdl_1_3_no_invariants_only;
pub use license_gfdl_1_3_no_invariants_only::LICENSE_GFDL_1_3_NO_INVARIANTS_ONLY;
mod license_gfdl_1_3_no_invariants_or_later;
pub use license_gfdl_1_3_no_invariants_or_later::LICENSE_GFDL_1_3_NO_INVARIANTS_OR_LATER;
mod license_gfdl_1_3_only;
pub use license_gfdl_1_3_only::LICENSE_GFDL_1_3_ONLY;
mod license_gfdl_1_3_or_later;
pub use license_gfdl_1_3_or_later::LICENSE_GFDL_1_3_OR_LATER;
mod license_giftware;
pub use license_giftware::LICENSE_GIFTWARE;
mod license_gl2ps;
pub use license_gl2ps::LICENSE_GL2PS;
mod license_glide;
pub use license_glide::LICENSE_GLIDE;
mod license_glulxe;
pub use license_glulxe::LICENSE_GLULXE;
mod license_glwtpl;
pub use license_glwtpl::LICENSE_GLWTPL;
mod license_gnuplot;
pub use license_gnuplot::LICENSE_GNUPLOT;
mod license_gpl_1_0_only;
pub use license_gpl_1_0_only::LICENSE_GPL_1_0_ONLY;
mod license_gpl_1_0_or_later;
pub use license_gpl_1_0_or_later::LICENSE_GPL_1_0_OR_LATER;
mod license_gpl_2_0_only;
pub use license_gpl_2_0_only::LICENSE_GPL_2_0_ONLY;
mod license_gpl_2_0_or_later;
pub use license_gpl_2_0_or_later::LICENSE_GPL_2_0_OR_LATER;
mod license_gpl_3_0_only;
pub use license_gpl_3_0_only::LICENSE_GPL_3_0_ONLY;
mod license_gpl_3_0_or_later;
pub use license_gpl_3_0_or_later::LICENSE_GPL_3_0_OR_LATER;
mod license_graphics_gems;
pub use license_graphics_gems::LICENSE_GRAPHICS_GEMS;
mod license_gsoap_1_3b;
pub use license_gsoap_1_3b::LICENSE_GSOAP_1_3B;
mod license_gtkbook;
pub use license_gtkbook::LICENSE_GTKBOOK;
mod license_gutmann;
pub use license_gutmann::LICENSE_GUTMANN;
mod license_haskellreport;
pub use license_haskellreport::LICENSE_HASKELLREPORT;
mod license_hdf5;
pub use license_hdf5::LICENSE_HDF5;
mod license_hdparm;
pub use license_hdparm::LICENSE_HDPARM;
mod license_hidapi;
pub use license_hidapi::LICENSE_HIDAPI;
mod license_hippocratic_2_1;
pub use license_hippocratic_2_1::LICENSE_HIPPOCRATIC_2_1;
mod license_hp_1986;
pub use license_hp_1986::LICENSE_HP_1986;
mod license_hp_1989;
pub use license_hp_1989::LICENSE_HP_1989;
mod license_hpnd;
pub use license_hpnd::LICENSE_HPND;
mod license_hpnd_dec;
pub use license_hpnd_dec::LICENSE_HPND_DEC;
mod license_hpnd_doc;
pub use license_hpnd_doc::LICENSE_HPND_DOC;
mod license_hpnd_doc_sell;
pub use license_hpnd_doc_sell::LICENSE_HPND_DOC_SELL;
mod license_hpnd_export_us;
pub use license_hpnd_export_us::LICENSE_HPND_EXPORT_US;
mod license_hpnd_export_us_acknowledgement;
pub use license_hpnd_export_us_acknowledgement::LICENSE_HPND_EXPORT_US_ACKNOWLEDGEMENT;
mod license_hpnd_export_us_modify;
pub use license_hpnd_export_us_modify::LICENSE_HPND_EXPORT_US_MODIFY;
mod license_hpnd_export2_us;
pub use license_hpnd_export2_us::LICENSE_HPND_EXPORT2_US;
mod license_hpnd_fenneberg_livingston;
pub use license_hpnd_fenneberg_livingston::LICENSE_HPND_FENNEBERG_LIVINGSTON;
mod license_hpnd_inria_imag;
pub use license_hpnd_inria_imag::LICENSE_HPND_INRIA_IMAG;
mod license_hpnd_intel;
pub use license_hpnd_intel::LICENSE_HPND_INTEL;
mod license_hpnd_kevlin_henney;
pub use license_hpnd_kevlin_henney::LICENSE_HPND_KEVLIN_HENNEY;
mod license_hpnd_markus_kuhn;
pub use license_hpnd_markus_kuhn::LICENSE_HPND_MARKUS_KUHN;
mod license_hpnd_merchantability_variant;
pub use license_hpnd_merchantability_variant::LICENSE_HPND_MERCHANTABILITY_VARIANT;
mod license_hpnd_mit_disclaimer;
pub use license_hpnd_mit_disclaimer::LICENSE_HPND_MIT_DISCLAIMER;
mod license_hpnd_netrek;
pub use license_hpnd_netrek::LICENSE_HPND_NETREK;
mod license_hpnd_pbmplus;
pub use license_hpnd_pbmplus::LICENSE_HPND_PBMPLUS;
mod license_hpnd_sell_mit_disclaimer_xserver;
pub use license_hpnd_sell_mit_disclaimer_xserver::LICENSE_HPND_SELL_MIT_DISCLAIMER_XSERVER;
mod license_hpnd_sell_regexpr;
pub use license_hpnd_sell_regexpr::LICENSE_HPND_SELL_REGEXPR;
mod license_hpnd_sell_variant;
pub use license_hpnd_sell_variant::LICENSE_HPND_SELL_VARIANT;
mod license_hpnd_sell_variant_critical_systems;
pub use license_hpnd_sell_variant_critical_systems::LICENSE_HPND_SELL_VARIANT_CRITICAL_SYSTEMS;
mod license_hpnd_sell_variant_mit_disclaimer;
pub use license_hpnd_sell_variant_mit_disclaimer::LICENSE_HPND_SELL_VARIANT_MIT_DISCLAIMER;
mod license_hpnd_sell_variant_mit_disclaimer_rev;
pub use license_hpnd_sell_variant_mit_disclaimer_rev::LICENSE_HPND_SELL_VARIANT_MIT_DISCLAIMER_REV;
mod license_hpnd_smc;
pub use license_hpnd_smc::LICENSE_HPND_SMC;
mod license_hpnd_uc;
pub use license_hpnd_uc::LICENSE_HPND_UC;
mod license_hpnd_uc_export_us;
pub use license_hpnd_uc_export_us::LICENSE_HPND_UC_EXPORT_US;
mod license_htmltidy;
pub use license_htmltidy::LICENSE_HTMLTIDY;
mod license_hyphen_bulgarian;
pub use license_hyphen_bulgarian::LICENSE_HYPHEN_BULGARIAN;
mod license_ibm_pibs;
pub use license_ibm_pibs::LICENSE_IBM_PIBS;
mod license_icu;
pub use license_icu::LICENSE_ICU;
mod license_iec_code_components_eula;
pub use license_iec_code_components_eula::LICENSE_IEC_CODE_COMPONENTS_EULA;
mod license_ijg;
pub use license_ijg::LICENSE_IJG;
mod license_ijg_short;
pub use license_ijg_short::LICENSE_IJG_SHORT;
mod license_imagemagick;
pub use license_imagemagick::LICENSE_IMAGEMAGICK;
mod license_imatix;
pub use license_imatix::LICENSE_IMATIX;
mod license_imlib2;
pub use license_imlib2::LICENSE_IMLIB2;
mod license_info_zip;
pub use license_info_zip::LICENSE_INFO_ZIP;
mod license_inner_net_2_0;
pub use license_inner_net_2_0::LICENSE_INNER_NET_2_0;
mod license_innosetup;
pub use license_innosetup::LICENSE_INNOSETUP;
mod license_intel;
pub use license_intel::LICENSE_INTEL;
mod license_intel_acpi;
pub use license_intel_acpi::LICENSE_INTEL_ACPI;
mod license_interbase_1_0;
pub use license_interbase_1_0::LICENSE_INTERBASE_1_0;
mod license_ipa;
pub use license_ipa::LICENSE_IPA;
mod license_ipl_1_0;
pub use license_ipl_1_0::LICENSE_IPL_1_0;
mod license_isc;
pub use license_isc::LICENSE_ISC;
mod license_isc_veillard;
pub use license_isc_veillard::LICENSE_ISC_VEILLARD;
mod license_iso_permission;
pub use license_iso_permission::LICENSE_ISO_PERMISSION;
mod license_jam;
pub use license_jam::LICENSE_JAM;
mod license_jasper_2_0;
pub use license_jasper_2_0::LICENSE_JASPER_2_0;
mod license_jove;
pub use license_jove::LICENSE_JOVE;
mod license_jpl_image;
pub use license_jpl_image::LICENSE_JPL_IMAGE;
mod license_jpnic;
pub use license_jpnic::LICENSE_JPNIC;
mod license_json;
pub use license_json::LICENSE_JSON;
mod license_kastrup;
pub use license_kastrup::LICENSE_KASTRUP;
mod license_kazlib;
pub use license_kazlib::LICENSE_KAZLIB;
mod license_knuth_ctan;
pub use license_knuth_ctan::LICENSE_KNUTH_CTAN;
mod license_lal_1_2;
pub use license_lal_1_2::LICENSE_LAL_1_2;
mod license_lal_1_3;
pub use license_lal_1_3::LICENSE_LAL_1_3;
mod license_latex2e;
pub use license_latex2e::LICENSE_LATEX2E;
mod license_latex2e_translated_notice;
pub use license_latex2e_translated_notice::LICENSE_LATEX2E_TRANSLATED_NOTICE;
mod license_leptonica;
pub use license_leptonica::LICENSE_LEPTONICA;
mod license_lgpl_2_0_only;
pub use license_lgpl_2_0_only::LICENSE_LGPL_2_0_ONLY;
mod license_lgpl_2_0_or_later;
pub use license_lgpl_2_0_or_later::LICENSE_LGPL_2_0_OR_LATER;
mod license_lgpl_2_1_only;
pub use license_lgpl_2_1_only::LICENSE_LGPL_2_1_ONLY;
mod license_lgpl_2_1_or_later;
pub use license_lgpl_2_1_or_later::LICENSE_LGPL_2_1_OR_LATER;
mod license_lgpl_3_0_only;
pub use license_lgpl_3_0_only::LICENSE_LGPL_3_0_ONLY;
mod license_lgpl_3_0_or_later;
pub use license_lgpl_3_0_or_later::LICENSE_LGPL_3_0_OR_LATER;
mod license_lgpllr;
pub use license_lgpllr::LICENSE_LGPLLR;
mod license_libpng;
pub use license_libpng::LICENSE_LIBPNG;
mod license_libpng_1_6_35;
pub use license_libpng_1_6_35::LICENSE_LIBPNG_1_6_35;
mod license_libpng_2_0;
pub use license_libpng_2_0::LICENSE_LIBPNG_2_0;
mod license_libselinux_1_0;
pub use license_libselinux_1_0::LICENSE_LIBSELINUX_1_0;
mod license_libtiff;
pub use license_libtiff::LICENSE_LIBTIFF;
mod license_libutil_david_nugent;
pub use license_libutil_david_nugent::LICENSE_LIBUTIL_DAVID_NUGENT;
mod license_liliq_p_1_1;
pub use license_liliq_p_1_1::LICENSE_LILIQ_P_1_1;
mod license_liliq_r_1_1;
pub use license_liliq_r_1_1::LICENSE_LILIQ_R_1_1;
mod license_liliq_rplus_1_1;
pub use license_liliq_rplus_1_1::LICENSE_LILIQ_RPLUS_1_1;
mod license_linux_man_pages_1_para;
pub use license_linux_man_pages_1_para::LICENSE_LINUX_MAN_PAGES_1_PARA;
mod license_linux_man_pages_copyleft;
pub use license_linux_man_pages_copyleft::LICENSE_LINUX_MAN_PAGES_COPYLEFT;
mod license_linux_man_pages_copyleft_2_para;
pub use license_linux_man_pages_copyleft_2_para::LICENSE_LINUX_MAN_PAGES_COPYLEFT_2_PARA;
mod license_linux_man_pages_copyleft_var;
pub use license_linux_man_pages_copyleft_var::LICENSE_LINUX_MAN_PAGES_COPYLEFT_VAR;
mod license_linux_openib;
pub use license_linux_openib::LICENSE_LINUX_OPENIB;
mod license_loop;
pub use license_loop::LICENSE_LOOP;
mod license_lpd_document;
pub use license_lpd_document::LICENSE_LPD_DOCUMENT;
mod license_lpl_1_0;
pub use license_lpl_1_0::LICENSE_LPL_1_0;
mod license_lpl_1_02;
pub use license_lpl_1_02::LICENSE_LPL_1_02;
mod license_lppl_1_0;
pub use license_lppl_1_0::LICENSE_LPPL_1_0;
mod license_lppl_1_1;
pub use license_lppl_1_1::LICENSE_LPPL_1_1;
mod license_lppl_1_2;
pub use license_lppl_1_2::LICENSE_LPPL_1_2;
mod license_lppl_1_3a;
pub use license_lppl_1_3a::LICENSE_LPPL_1_3A;
mod license_lppl_1_3c;
pub use license_lppl_1_3c::LICENSE_LPPL_1_3C;
mod license_lsof;
pub use license_lsof::LICENSE_LSOF;
mod license_lucida_bitmap_fonts;
pub use license_lucida_bitmap_fonts::LICENSE_LUCIDA_BITMAP_FONTS;
mod license_lzma_sdk_9_11_to_9_20;
pub use license_lzma_sdk_9_11_to_9_20::LICENSE_LZMA_SDK_9_11_TO_9_20;
mod license_lzma_sdk_9_22;
pub use license_lzma_sdk_9_22::LICENSE_LZMA_SDK_9_22;
mod license_mackerras_3_clause;
pub use license_mackerras_3_clause::LICENSE_MACKERRAS_3_CLAUSE;
mod license_mackerras_3_clause_acknowledgment;
pub use license_mackerras_3_clause_acknowledgment::LICENSE_MACKERRAS_3_CLAUSE_ACKNOWLEDGMENT;
mod license_magaz;
pub use license_magaz::LICENSE_MAGAZ;
mod license_mailprio;
pub use license_mailprio::LICENSE_MAILPRIO;
mod license_makeindex;
pub use license_makeindex::LICENSE_MAKEINDEX;
mod license_man2html;
pub use license_man2html::LICENSE_MAN2HTML;
mod license_martin_birgmeier;
pub use license_martin_birgmeier::LICENSE_MARTIN_BIRGMEIER;
mod license_mcphee_slideshow;
pub use license_mcphee_slideshow::LICENSE_MCPHEE_SLIDESHOW;
mod license_metamail;
pub use license_metamail::LICENSE_METAMAIL;
mod license_minpack;
pub use license_minpack::LICENSE_MINPACK;
mod license_mips;
pub use license_mips::LICENSE_MIPS;
mod license_miros;
pub use license_miros::LICENSE_MIROS;
mod license_mit;
pub use license_mit::LICENSE_MIT;
mod license_mit_0;
pub use license_mit_0::LICENSE_MIT_0;
mod license_mit_advertising;
pub use license_mit_advertising::LICENSE_MIT_ADVERTISING;
mod license_mit_click;
pub use license_mit_click::LICENSE_MIT_CLICK;
mod license_mit_cmu;
pub use license_mit_cmu::LICENSE_MIT_CMU;
mod license_mit_enna;
pub use license_mit_enna::LICENSE_MIT_ENNA;
mod license_mit_feh;
pub use license_mit_feh::LICENSE_MIT_FEH;
mod license_mit_festival;
pub use license_mit_festival::LICENSE_MIT_FESTIVAL;
mod license_mit_khronos_old;
pub use license_mit_khronos_old::LICENSE_MIT_KHRONOS_OLD;
mod license_mit_modern_variant;
pub use license_mit_modern_variant::LICENSE_MIT_MODERN_VARIANT;
mod license_mit_open_group;
pub use license_mit_open_group::LICENSE_MIT_OPEN_GROUP;
mod license_mit_stk;
pub use license_mit_stk::LICENSE_MIT_STK;
mod license_mit_testregex;
pub use license_mit_testregex::LICENSE_MIT_TESTREGEX;
mod license_mit_wu;
pub use license_mit_wu::LICENSE_MIT_WU;
mod license_mitnfa;
pub use license_mitnfa::LICENSE_MITNFA;
mod license_mmixware;
pub use license_mmixware::LICENSE_MMIXWARE;
mod license_mmpl_1_0_1;
pub use license_mmpl_1_0_1::LICENSE_MMPL_1_0_1;
mod license_motosoto;
pub use license_motosoto::LICENSE_MOTOSOTO;
mod license_mpeg_ssg;
pub use license_mpeg_ssg::LICENSE_MPEG_SSG;
mod license_mpi_permissive;
pub use license_mpi_permissive::LICENSE_MPI_PERMISSIVE;
mod license_mpich2;
pub use license_mpich2::LICENSE_MPICH2;
mod license_mpl_1_0;
pub use license_mpl_1_0::LICENSE_MPL_1_0;
mod license_mpl_1_1;
pub use license_mpl_1_1::LICENSE_MPL_1_1;
mod license_mpl_2_0;
pub use license_mpl_2_0::LICENSE_MPL_2_0;
mod license_mpl_2_0_no_copyleft_exception;
pub use license_mpl_2_0_no_copyleft_exception::LICENSE_MPL_2_0_NO_COPYLEFT_EXCEPTION;
mod license_mplus;
pub use license_mplus::LICENSE_MPLUS;
mod license_ms_lpl;
pub use license_ms_lpl::LICENSE_MS_LPL;
mod license_ms_pl;
pub use license_ms_pl::LICENSE_MS_PL;
mod license_ms_rl;
pub use license_ms_rl::LICENSE_MS_RL;
mod license_mtll;
pub use license_mtll::LICENSE_MTLL;
mod license_mulanpsl_1_0;
pub use license_mulanpsl_1_0::LICENSE_MULANPSL_1_0;
mod license_mulanpsl_2_0;
pub use license_mulanpsl_2_0::LICENSE_MULANPSL_2_0;
mod license_multics;
pub use license_multics::LICENSE_MULTICS;
mod license_mup;
pub use license_mup::LICENSE_MUP;
mod license_naist_2003;
pub use license_naist_2003::LICENSE_NAIST_2003;
mod license_nasa_1_3;
pub use license_nasa_1_3::LICENSE_NASA_1_3;
mod license_naumen;
pub use license_naumen::LICENSE_NAUMEN;
mod license_nbpl_1_0;
pub use license_nbpl_1_0::LICENSE_NBPL_1_0;
mod license_ncbi_pd;
pub use license_ncbi_pd::LICENSE_NCBI_PD;
mod license_ncgl_uk_2_0;
pub use license_ncgl_uk_2_0::LICENSE_NCGL_UK_2_0;
mod license_ncl;
pub use license_ncl::LICENSE_NCL;
mod license_ncsa;
pub use license_ncsa::LICENSE_NCSA;
mod license_netcdf;
pub use license_netcdf::LICENSE_NETCDF;
mod license_newsletr;
pub use license_newsletr::LICENSE_NEWSLETR;
mod license_ngpl;
pub use license_ngpl::LICENSE_NGPL;
mod license_ngrep;
pub use license_ngrep::LICENSE_NGREP;
mod license_nicta_1_0;
pub use license_nicta_1_0::LICENSE_NICTA_1_0;
mod license_nist_pd;
pub use license_nist_pd::LICENSE_NIST_PD;
mod license_nist_pd_fallback;
pub use license_nist_pd_fallback::LICENSE_NIST_PD_FALLBACK;
mod license_nist_pd_tnt;
pub use license_nist_pd_tnt::LICENSE_NIST_PD_TNT;
mod license_nist_software;
pub use license_nist_software::LICENSE_NIST_SOFTWARE;
mod license_nlod_1_0;
pub use license_nlod_1_0::LICENSE_NLOD_1_0;
mod license_nlod_2_0;
pub use license_nlod_2_0::LICENSE_NLOD_2_0;
mod license_nlpl;
pub use license_nlpl::LICENSE_NLPL;
mod license_nokia;
pub use license_nokia::LICENSE_NOKIA;
mod license_nosl;
pub use license_nosl::LICENSE_NOSL;
mod license_noweb;
pub use license_noweb::LICENSE_NOWEB;
mod license_npl_1_0;
pub use license_npl_1_0::LICENSE_NPL_1_0;
mod license_npl_1_1;
pub use license_npl_1_1::LICENSE_NPL_1_1;
mod license_nposl_3_0;
pub use license_nposl_3_0::LICENSE_NPOSL_3_0;
mod license_nrl;
pub use license_nrl::LICENSE_NRL;
mod license_ntia_pd;
pub use license_ntia_pd::LICENSE_NTIA_PD;
mod license_ntp;
pub use license_ntp::LICENSE_NTP;
mod license_ntp_0;
pub use license_ntp_0::LICENSE_NTP_0;
mod license_o_uda_1_0;
pub use license_o_uda_1_0::LICENSE_O_UDA_1_0;
mod license_oar;
pub use license_oar::LICENSE_OAR;
mod license_occt_pl;
pub use license_occt_pl::LICENSE_OCCT_PL;
mod license_oclc_2_0;
pub use license_oclc_2_0::LICENSE_OCLC_2_0;
mod license_odbl_1_0;
pub use license_odbl_1_0::LICENSE_ODBL_1_0;
mod license_odc_by_1_0;
pub use license_odc_by_1_0::LICENSE_ODC_BY_1_0;
mod license_offis;
pub use license_offis::LICENSE_OFFIS;
mod license_ofl_1_0;
pub use license_ofl_1_0::LICENSE_OFL_1_0;
mod license_ofl_1_0_no_rfn;
pub use license_ofl_1_0_no_rfn::LICENSE_OFL_1_0_NO_RFN;
mod license_ofl_1_0_rfn;
pub use license_ofl_1_0_rfn::LICENSE_OFL_1_0_RFN;
mod license_ofl_1_1;
pub use license_ofl_1_1::LICENSE_OFL_1_1;
mod license_ofl_1_1_no_rfn;
pub use license_ofl_1_1_no_rfn::LICENSE_OFL_1_1_NO_RFN;
mod license_ofl_1_1_rfn;
pub use license_ofl_1_1_rfn::LICENSE_OFL_1_1_RFN;
mod license_ogc_1_0;
pub use license_ogc_1_0::LICENSE_OGC_1_0;
mod license_ogdl_taiwan_1_0;
pub use license_ogdl_taiwan_1_0::LICENSE_OGDL_TAIWAN_1_0;
mod license_ogl_canada_2_0;
pub use license_ogl_canada_2_0::LICENSE_OGL_CANADA_2_0;
mod license_ogl_uk_1_0;
pub use license_ogl_uk_1_0::LICENSE_OGL_UK_1_0;
mod license_ogl_uk_2_0;
pub use license_ogl_uk_2_0::LICENSE_OGL_UK_2_0;
mod license_ogl_uk_3_0;
pub use license_ogl_uk_3_0::LICENSE_OGL_UK_3_0;
mod license_ogtsl;
pub use license_ogtsl::LICENSE_OGTSL;
mod license_oldap_1_1;
pub use license_oldap_1_1::LICENSE_OLDAP_1_1;
mod license_oldap_1_2;
pub use license_oldap_1_2::LICENSE_OLDAP_1_2;
mod license_oldap_1_3;
pub use license_oldap_1_3::LICENSE_OLDAP_1_3;
mod license_oldap_1_4;
pub use license_oldap_1_4::LICENSE_OLDAP_1_4;
mod license_oldap_2_0;
pub use license_oldap_2_0::LICENSE_OLDAP_2_0;
mod license_oldap_2_0_1;
pub use license_oldap_2_0_1::LICENSE_OLDAP_2_0_1;
mod license_oldap_2_1;
pub use license_oldap_2_1::LICENSE_OLDAP_2_1;
mod license_oldap_2_2;
pub use license_oldap_2_2::LICENSE_OLDAP_2_2;
mod license_oldap_2_2_1;
pub use license_oldap_2_2_1::LICENSE_OLDAP_2_2_1;
mod license_oldap_2_2_2;
pub use license_oldap_2_2_2::LICENSE_OLDAP_2_2_2;
mod license_oldap_2_3;
pub use license_oldap_2_3::LICENSE_OLDAP_2_3;
mod license_oldap_2_4;
pub use license_oldap_2_4::LICENSE_OLDAP_2_4;
mod license_oldap_2_5;
pub use license_oldap_2_5::LICENSE_OLDAP_2_5;
mod license_oldap_2_6;
pub use license_oldap_2_6::LICENSE_OLDAP_2_6;
mod license_oldap_2_7;
pub use license_oldap_2_7::LICENSE_OLDAP_2_7;
mod license_oldap_2_8;
pub use license_oldap_2_8::LICENSE_OLDAP_2_8;
mod license_olfl_1_3;
pub use license_olfl_1_3::LICENSE_OLFL_1_3;
mod license_oml;
pub use license_oml::LICENSE_OML;
mod license_openmdw_1_0;
pub use license_openmdw_1_0::LICENSE_OPENMDW_1_0;
mod license_openpbs_2_3;
pub use license_openpbs_2_3::LICENSE_OPENPBS_2_3;
mod license_openssl;
pub use license_openssl::LICENSE_OPENSSL;
mod license_openssl_standalone;
pub use license_openssl_standalone::LICENSE_OPENSSL_STANDALONE;
mod license_openvision;
pub use license_openvision::LICENSE_OPENVISION;
mod license_opl_1_0;
pub use license_opl_1_0::LICENSE_OPL_1_0;
mod license_opl_uk_3_0;
pub use license_opl_uk_3_0::LICENSE_OPL_UK_3_0;
mod license_opubl_1_0;
pub use license_opubl_1_0::LICENSE_OPUBL_1_0;
mod license_osc_1_0;
pub use license_osc_1_0::LICENSE_OSC_1_0;
mod license_oset_pl_2_1;
pub use license_oset_pl_2_1::LICENSE_OSET_PL_2_1;
mod license_osl_1_0;
pub use license_osl_1_0::LICENSE_OSL_1_0;
mod license_osl_1_1;
pub use license_osl_1_1::LICENSE_OSL_1_1;
mod license_osl_2_0;
pub use license_osl_2_0::LICENSE_OSL_2_0;
mod license_osl_2_1;
pub use license_osl_2_1::LICENSE_OSL_2_1;
mod license_osl_3_0;
pub use license_osl_3_0::LICENSE_OSL_3_0;
mod license_ossp;
pub use license_ossp::LICENSE_OSSP;
mod license_padl;
pub use license_padl::LICENSE_PADL;
mod license_paratype_free_font_1_3;
pub use license_paratype_free_font_1_3::LICENSE_PARATYPE_FREE_FONT_1_3;
mod license_parity_6_0_0;
pub use license_parity_6_0_0::LICENSE_PARITY_6_0_0;
mod license_parity_7_0_0;
pub use license_parity_7_0_0::LICENSE_PARITY_7_0_0;
mod license_pddl_1_0;
pub use license_pddl_1_0::LICENSE_PDDL_1_0;
mod license_php_3_0;
pub use license_php_3_0::LICENSE_PHP_3_0;
mod license_php_3_01;
pub use license_php_3_01::LICENSE_PHP_3_01;
mod license_pixar;
pub use license_pixar::LICENSE_PIXAR;
mod license_pkgconf;
pub use license_pkgconf::LICENSE_PKGCONF;
mod license_plexus;
pub use license_plexus::LICENSE_PLEXUS;
mod license_pnmstitch;
pub use license_pnmstitch::LICENSE_PNMSTITCH;
mod license_polyform_noncommercial_1_0_0;
pub use license_polyform_noncommercial_1_0_0::LICENSE_POLYFORM_NONCOMMERCIAL_1_0_0;
mod license_polyform_small_business_1_0_0;
pub use license_polyform_small_business_1_0_0::LICENSE_POLYFORM_SMALL_BUSINESS_1_0_0;
mod license_postgresql;
pub use license_postgresql::LICENSE_POSTGRESQL;
mod license_ppl;
pub use license_ppl::LICENSE_PPL;
mod license_psf_2_0;
pub use license_psf_2_0::LICENSE_PSF_2_0;
mod license_psfrag;
pub use license_psfrag::LICENSE_PSFRAG;
mod license_psutils;
pub use license_psutils::LICENSE_PSUTILS;
mod license_python_2_0;
pub use license_python_2_0::LICENSE_PYTHON_2_0;
mod license_python_2_0_1;
pub use license_python_2_0_1::LICENSE_PYTHON_2_0_1;
mod license_python_ldap;
pub use license_python_ldap::LICENSE_PYTHON_LDAP;
mod license_qhull;
pub use license_qhull::LICENSE_QHULL;
mod license_qpl_1_0;
pub use license_qpl_1_0::LICENSE_QPL_1_0;
mod license_qpl_1_0_inria_2004;
pub use license_qpl_1_0_inria_2004::LICENSE_QPL_1_0_INRIA_2004;
mod license_radvd;
pub use license_radvd::LICENSE_RADVD;
mod license_rdisc;
pub use license_rdisc::LICENSE_RDISC;
mod license_rhecos_1_1;
pub use license_rhecos_1_1::LICENSE_RHECOS_1_1;
mod license_rpl_1_1;
pub use license_rpl_1_1::LICENSE_RPL_1_1;
mod license_rpl_1_5;
pub use license_rpl_1_5::LICENSE_RPL_1_5;
mod license_rpsl_1_0;
pub use license_rpsl_1_0::LICENSE_RPSL_1_0;
mod license_rsa_md;
pub use license_rsa_md::LICENSE_RSA_MD;
mod license_rscpl;
pub use license_rscpl::LICENSE_RSCPL;
mod license_ruby;
pub use license_ruby::LICENSE_RUBY;
mod license_ruby_pty;
pub use license_ruby_pty::LICENSE_RUBY_PTY;
mod license_sax_pd;
pub use license_sax_pd::LICENSE_SAX_PD;
mod license_sax_pd_2_0;
pub use license_sax_pd_2_0::LICENSE_SAX_PD_2_0;
mod license_saxpath;
pub use license_saxpath::LICENSE_SAXPATH;
mod license_scea;
pub use license_scea::LICENSE_SCEA;
mod license_schemereport;
pub use license_schemereport::LICENSE_SCHEMEREPORT;
mod license_sendmail;
pub use license_sendmail::LICENSE_SENDMAIL;
mod license_sendmail_8_23;
pub use license_sendmail_8_23::LICENSE_SENDMAIL_8_23;
mod license_sendmail_open_source_1_1;
pub use license_sendmail_open_source_1_1::LICENSE_SENDMAIL_OPEN_SOURCE_1_1;
mod license_sgi_b_1_0;
pub use license_sgi_b_1_0::LICENSE_SGI_B_1_0;
mod license_sgi_b_1_1;
pub use license_sgi_b_1_1::LICENSE_SGI_B_1_1;
mod license_sgi_b_2_0;
pub use license_sgi_b_2_0::LICENSE_SGI_B_2_0;
mod license_sgi_opengl;
pub use license_sgi_opengl::LICENSE_SGI_OPENGL;
mod license_sgmlug_pm;
pub use license_sgmlug_pm::LICENSE_SGMLUG_PM;
mod license_sgp4;
pub use license_sgp4::LICENSE_SGP4;
mod license_shl_0_5;
pub use license_shl_0_5::LICENSE_SHL_0_5;
mod license_shl_0_51;
pub use license_shl_0_51::LICENSE_SHL_0_51;
mod license_simpl_2_0;
pub use license_simpl_2_0::LICENSE_SIMPL_2_0;
mod license_sissl;
pub use license_sissl::LICENSE_SISSL;
mod license_sissl_1_2;
pub use license_sissl_1_2::LICENSE_SISSL_1_2;
mod license_sl;
pub use license_sl::LICENSE_SL;
mod license_sleepycat;
pub use license_sleepycat::LICENSE_SLEEPYCAT;
mod license_smail_gpl;
pub use license_smail_gpl::LICENSE_SMAIL_GPL;
mod license_smlnj;
pub use license_smlnj::LICENSE_SMLNJ;
mod license_smppl;
pub use license_smppl::LICENSE_SMPPL;
mod license_snia;
pub use license_snia::LICENSE_SNIA;
mod license_snprintf;
pub use license_snprintf::LICENSE_SNPRINTF;
mod license_sofa;
pub use license_sofa::LICENSE_SOFA;
mod license_softsurfer;
pub use license_softsurfer::LICENSE_SOFTSURFER;
mod license_soundex;
pub use license_soundex::LICENSE_SOUNDEX;
mod license_spencer_86;
pub use license_spencer_86::LICENSE_SPENCER_86;
mod license_spencer_94;
pub use license_spencer_94::LICENSE_SPENCER_94;
mod license_spencer_99;
pub use license_spencer_99::LICENSE_SPENCER_99;
mod license_spl_1_0;
pub use license_spl_1_0::LICENSE_SPL_1_0;
mod license_ssh_keyscan;
pub use license_ssh_keyscan::LICENSE_SSH_KEYSCAN;
mod license_ssh_openssh;
pub use license_ssh_openssh::LICENSE_SSH_OPENSSH;
mod license_ssh_short;
pub use license_ssh_short::LICENSE_SSH_SHORT;
mod license_ssleay_standalone;
pub use license_ssleay_standalone::LICENSE_SSLEAY_STANDALONE;
mod license_sspl_1_0;
pub use license_sspl_1_0::LICENSE_SSPL_1_0;
mod license_sugarcrm_1_1_3;
pub use license_sugarcrm_1_1_3::LICENSE_SUGARCRM_1_1_3;
mod license_sul_1_0;
pub use license_sul_1_0::LICENSE_SUL_1_0;
mod license_sun_ppp;
pub use license_sun_ppp::LICENSE_SUN_PPP;
mod license_sun_ppp_2000;
pub use license_sun_ppp_2000::LICENSE_SUN_PPP_2000;
mod license_sunpro;
pub use license_sunpro::LICENSE_SUNPRO;
mod license_swl;
pub use license_swl::LICENSE_SWL;
mod license_swrule;
pub use license_swrule::LICENSE_SWRULE;
mod license_symlinks;
pub use license_symlinks::LICENSE_SYMLINKS;
mod license_tapr_ohl_1_0;
pub use license_tapr_ohl_1_0::LICENSE_TAPR_OHL_1_0;
mod license_tcl;
pub use license_tcl::LICENSE_TCL;
mod license_tcp_wrappers;
pub use license_tcp_wrappers::LICENSE_TCP_WRAPPERS;
mod license_tekhvc;
pub use license_tekhvc::LICENSE_TEKHVC;
mod license_termreadkey;
pub use license_termreadkey::LICENSE_TERMREADKEY;
mod license_tgppl_1_0;
pub use license_tgppl_1_0::LICENSE_TGPPL_1_0;
mod license_thirdeye;
pub use license_thirdeye::LICENSE_THIRDEYE;
mod license_threeparttable;
pub use license_threeparttable::LICENSE_THREEPARTTABLE;
mod license_tmate;
pub use license_tmate::LICENSE_TMATE;
mod license_torque_1_1;
pub use license_torque_1_1::LICENSE_TORQUE_1_1;
mod license_tosl;
pub use license_tosl::LICENSE_TOSL;
mod license_tpdl;
pub use license_tpdl::LICENSE_TPDL;
mod license_tpl_1_0;
pub use license_tpl_1_0::LICENSE_TPL_1_0;
mod license_trustedqsl;
pub use license_trustedqsl::LICENSE_TRUSTEDQSL;
mod license_ttwl;
pub use license_ttwl::LICENSE_TTWL;
mod license_ttyp0;
pub use license_ttyp0::LICENSE_TTYP0;
mod license_tu_berlin_1_0;
pub use license_tu_berlin_1_0::LICENSE_TU_BERLIN_1_0;
mod license_tu_berlin_2_0;
pub use license_tu_berlin_2_0::LICENSE_TU_BERLIN_2_0;
mod license_ubuntu_font_1_0;
pub use license_ubuntu_font_1_0::LICENSE_UBUNTU_FONT_1_0;
mod license_ucar;
pub use license_ucar::LICENSE_UCAR;
mod license_ucl_1_0;
pub use license_ucl_1_0::LICENSE_UCL_1_0;
mod license_ulem;
pub use license_ulem::LICENSE_ULEM;
mod license_umich_merit;
pub use license_umich_merit::LICENSE_UMICH_MERIT;
mod license_unicode_3_0;
pub use license_unicode_3_0::LICENSE_UNICODE_3_0;
mod license_unicode_dfs_2015;
pub use license_unicode_dfs_2015::LICENSE_UNICODE_DFS_2015;
mod license_unicode_dfs_2016;
pub use license_unicode_dfs_2016::LICENSE_UNICODE_DFS_2016;
mod license_unicode_tou;
pub use license_unicode_tou::LICENSE_UNICODE_TOU;
mod license_unixcrypt;
pub use license_unixcrypt::LICENSE_UNIXCRYPT;
mod license_unlicense;
pub use license_unlicense::LICENSE_UNLICENSE;
mod license_unlicense_libtelnet;
pub use license_unlicense_libtelnet::LICENSE_UNLICENSE_LIBTELNET;
mod license_unlicense_libwhirlpool;
pub use license_unlicense_libwhirlpool::LICENSE_UNLICENSE_LIBWHIRLPOOL;
mod license_unrar;
pub use license_unrar::LICENSE_UNRAR;
mod license_upl_1_0;
pub use license_upl_1_0::LICENSE_UPL_1_0;
mod license_urt_rle;
pub use license_urt_rle::LICENSE_URT_RLE;
mod license_vim;
pub use license_vim::LICENSE_VIM;
mod license_vixie_cron;
pub use license_vixie_cron::LICENSE_VIXIE_CRON;
mod license_vostrom;
pub use license_vostrom::LICENSE_VOSTROM;
mod license_vsl_1_0;
pub use license_vsl_1_0::LICENSE_VSL_1_0;
mod license_w3c;
pub use license_w3c::LICENSE_W3C;
mod license_w3c_19980720;
pub use license_w3c_19980720::LICENSE_W3C_19980720;
mod license_w3c_20150513;
pub use license_w3c_20150513::LICENSE_W3C_20150513;
mod license_w3m;
pub use license_w3m::LICENSE_W3M;
mod license_watcom_1_0;
pub use license_watcom_1_0::LICENSE_WATCOM_1_0;
mod license_widget_workshop;
pub use license_widget_workshop::LICENSE_WIDGET_WORKSHOP;
mod license_wordnet;
pub use license_wordnet::LICENSE_WORDNET;
mod license_wsuipa;
pub use license_wsuipa::LICENSE_WSUIPA;
mod license_wtfnmfpl;
pub use license_wtfnmfpl::LICENSE_WTFNMFPL;
mod license_wtfpl;
pub use license_wtfpl::LICENSE_WTFPL;
mod license_wwl;
pub use license_wwl::LICENSE_WWL;
mod license_x11;
pub use license_x11::LICENSE_X11;
mod license_x11_distribute_modifications_variant;
pub use license_x11_distribute_modifications_variant::LICENSE_X11_DISTRIBUTE_MODIFICATIONS_VARIANT;
mod license_x11_no_permit_persons;
pub use license_x11_no_permit_persons::LICENSE_X11_NO_PERMIT_PERSONS;
mod license_x11_swapped;
pub use license_x11_swapped::LICENSE_X11_SWAPPED;
mod license_xdebug_1_03;
pub use license_xdebug_1_03::LICENSE_XDEBUG_1_03;
mod license_xerox;
pub use license_xerox::LICENSE_XEROX;
mod license_xfig;
pub use license_xfig::LICENSE_XFIG;
mod license_xfree86_1_1;
pub use license_xfree86_1_1::LICENSE_XFREE86_1_1;
mod license_xinetd;
pub use license_xinetd::LICENSE_XINETD;
mod license_xkeyboard_config_zinoviev;
pub use license_xkeyboard_config_zinoviev::LICENSE_XKEYBOARD_CONFIG_ZINOVIEV;
mod license_xlock;
pub use license_xlock::LICENSE_XLOCK;
mod license_xnet;
pub use license_xnet::LICENSE_XNET;
mod license_xpp;
pub use license_xpp::LICENSE_XPP;
mod license_xskat;
pub use license_xskat::LICENSE_XSKAT;
mod license_xzoom;
pub use license_xzoom::LICENSE_XZOOM;
mod license_ypl_1_0;
pub use license_ypl_1_0::LICENSE_YPL_1_0;
mod license_ypl_1_1;
pub use license_ypl_1_1::LICENSE_YPL_1_1;
mod license_zed;
pub use license_zed::LICENSE_ZED;
mod license_zeeff;
pub use license_zeeff::LICENSE_ZEEFF;
mod license_zend_2_0;
pub use license_zend_2_0::LICENSE_ZEND_2_0;
mod license_zimbra_1_3;
pub use license_zimbra_1_3::LICENSE_ZIMBRA_1_3;
mod license_zimbra_1_4;
pub use license_zimbra_1_4::LICENSE_ZIMBRA_1_4;
mod license_zlib;
pub use license_zlib::LICENSE_ZLIB;
mod license_zlib_acknowledgement;
pub use license_zlib_acknowledgement::LICENSE_ZLIB_ACKNOWLEDGEMENT;
mod license_zpl_1_1;
pub use license_zpl_1_1::LICENSE_ZPL_1_1;
mod license_zpl_2_0;
pub use license_zpl_2_0::LICENSE_ZPL_2_0;
mod license_zpl_2_1;
pub use license_zpl_2_1::LICENSE_ZPL_2_1;
mod license_agpl_1_0;
pub use license_agpl_1_0::LICENSE_AGPL_1_0;
mod license_agpl_3_0;
pub use license_agpl_3_0::LICENSE_AGPL_3_0;
mod license_bsd_2_clause_freebsd;
pub use license_bsd_2_clause_freebsd::LICENSE_BSD_2_CLAUSE_FREEBSD;
mod license_bsd_2_clause_netbsd;
pub use license_bsd_2_clause_netbsd::LICENSE_BSD_2_CLAUSE_NETBSD;
mod license_bzip2_1_0_5;
pub use license_bzip2_1_0_5::LICENSE_BZIP2_1_0_5;
mod license_ecos_2_0;
pub use license_ecos_2_0::LICENSE_ECOS_2_0;
mod license_gfdl_1_1;
pub use license_gfdl_1_1::LICENSE_GFDL_1_1;
mod license_gfdl_1_2;
pub use license_gfdl_1_2::LICENSE_GFDL_1_2;
mod license_gfdl_1_3;
pub use license_gfdl_1_3::LICENSE_GFDL_1_3;
mod license_gpl_1_0;
pub use license_gpl_1_0::LICENSE_GPL_1_0;
mod license_gpl_1_0plus;
pub use license_gpl_1_0plus::LICENSE_GPL_1_0PLUS;
mod license_gpl_2_0;
pub use license_gpl_2_0::LICENSE_GPL_2_0;
mod license_gpl_2_0plus;
pub use license_gpl_2_0plus::LICENSE_GPL_2_0PLUS;
mod license_gpl_2_0_with_autoconf_exception;
pub use license_gpl_2_0_with_autoconf_exception::LICENSE_GPL_2_0_WITH_AUTOCONF_EXCEPTION;
mod license_gpl_2_0_with_bison_exception;
pub use license_gpl_2_0_with_bison_exception::LICENSE_GPL_2_0_WITH_BISON_EXCEPTION;
mod license_gpl_2_0_with_classpath_exception;
pub use license_gpl_2_0_with_classpath_exception::LICENSE_GPL_2_0_WITH_CLASSPATH_EXCEPTION;
mod license_gpl_2_0_with_font_exception;
pub use license_gpl_2_0_with_font_exception::LICENSE_GPL_2_0_WITH_FONT_EXCEPTION;
mod license_gpl_2_0_with_gcc_exception;
pub use license_gpl_2_0_with_gcc_exception::LICENSE_GPL_2_0_WITH_GCC_EXCEPTION;
mod license_gpl_3_0;
pub use license_gpl_3_0::LICENSE_GPL_3_0;
mod license_gpl_3_0plus;
pub use license_gpl_3_0plus::LICENSE_GPL_3_0PLUS;
mod license_gpl_3_0_with_autoconf_exception;
pub use license_gpl_3_0_with_autoconf_exception::LICENSE_GPL_3_0_WITH_AUTOCONF_EXCEPTION;
mod license_gpl_3_0_with_gcc_exception;
pub use license_gpl_3_0_with_gcc_exception::LICENSE_GPL_3_0_WITH_GCC_EXCEPTION;
mod license_lgpl_2_0;
pub use license_lgpl_2_0::LICENSE_LGPL_2_0;
mod license_lgpl_2_0plus;
pub use license_lgpl_2_0plus::LICENSE_LGPL_2_0PLUS;
mod license_lgpl_2_1;
pub use license_lgpl_2_1::LICENSE_LGPL_2_1;
mod license_lgpl_2_1plus;
pub use license_lgpl_2_1plus::LICENSE_LGPL_2_1PLUS;
mod license_lgpl_3_0;
pub use license_lgpl_3_0::LICENSE_LGPL_3_0;
mod license_lgpl_3_0plus;
pub use license_lgpl_3_0plus::LICENSE_LGPL_3_0PLUS;
mod license_net_snmp;
pub use license_net_snmp::LICENSE_NET_SNMP;
mod license_nunit;
pub use license_nunit::LICENSE_NUNIT;
mod license_standardml_nj;
pub use license_standardml_nj::LICENSE_STANDARDML_NJ;
mod license_wxwindows;
pub use license_wxwindows::LICENSE_WXWINDOWS;
